// Code generated by buttplug-generate; DO NOT EDIT.

// Package schema contains the Buttplug message schema for version 3.
package schema

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"libdb.so/go-buttplug/schema/ptr"
	"log/slog"
)

// MessageType is the type string used to identify a buttplug.io message from the wire.
type MessageType string

// All defined message types.
const (
	// MessageTypeDeviceAdded is the type string for a [DeviceAddedMessage].
	MessageTypeDeviceAdded MessageType = "DeviceAdded"
	// MessageTypeDeviceList is the type string for a [DeviceListMessage].
	MessageTypeDeviceList MessageType = "DeviceList"
	// MessageTypeDeviceRemoved is the type string for a [DeviceRemovedMessage].
	MessageTypeDeviceRemoved MessageType = "DeviceRemoved"
	// MessageTypeError is the type string for a [ErrorMessage].
	MessageTypeError MessageType = "Error"
	// MessageTypeLinearCmd is the type string for a [LinearCmdMessage].
	MessageTypeLinearCmd MessageType = "LinearCmd"
	// MessageTypeOK is the type string for a [OKMessage].
	MessageTypeOK MessageType = "Ok"
	// MessageTypePing is the type string for a [PingMessage].
	MessageTypePing MessageType = "Ping"
	// MessageTypeRawReadCmd is the type string for a [RawReadCmdMessage].
	MessageTypeRawReadCmd MessageType = "RawReadCmd"
	// MessageTypeRawReading is the type string for a [RawReadingMessage].
	MessageTypeRawReading MessageType = "RawReading"
	// MessageTypeRawSubscribeCmd is the type string for a [RawSubscribeCmdMessage].
	MessageTypeRawSubscribeCmd MessageType = "RawSubscribeCmd"
	// MessageTypeRawUnsubscribeCmd is the type string for a [RawUnsubscribeCmdMessage].
	MessageTypeRawUnsubscribeCmd MessageType = "RawUnsubscribeCmd"
	// MessageTypeRawWriteCmd is the type string for a [RawWriteCmdMessage].
	MessageTypeRawWriteCmd MessageType = "RawWriteCmd"
	// MessageTypeRequestDeviceList is the type string for a [RequestDeviceListMessage].
	MessageTypeRequestDeviceList MessageType = "RequestDeviceList"
	// MessageTypeRequestServerInfo is the type string for a [RequestServerInfoMessage].
	MessageTypeRequestServerInfo MessageType = "RequestServerInfo"
	// MessageTypeRotateCmd is the type string for a [RotateCmdMessage].
	MessageTypeRotateCmd MessageType = "RotateCmd"
	// MessageTypeScalarCmd is the type string for a [ScalarCmdMessage].
	MessageTypeScalarCmd MessageType = "ScalarCmd"
	// MessageTypeScanningFinished is the type string for a [ScanningFinishedMessage].
	MessageTypeScanningFinished MessageType = "ScanningFinished"
	// MessageTypeSensorReadCmd is the type string for a [SensorReadCmdMessage].
	MessageTypeSensorReadCmd MessageType = "SensorReadCmd"
	// MessageTypeSensorReading is the type string for a [SensorReadingMessage].
	MessageTypeSensorReading MessageType = "SensorReading"
	// MessageTypeSensorSubscribeCmd is the type string for a [SensorSubscribeCmdMessage].
	MessageTypeSensorSubscribeCmd MessageType = "SensorSubscribeCmd"
	// MessageTypeSensorUnsubscribeCmd is the type string for a [SensorUnsubscribeCmdMessage].
	MessageTypeSensorUnsubscribeCmd MessageType = "SensorUnsubscribeCmd"
	// MessageTypeServerInfo is the type string for a [ServerInfoMessage].
	MessageTypeServerInfo MessageType = "ServerInfo"
	// MessageTypeStartScanning is the type string for a [StartScanningMessage].
	MessageTypeStartScanning MessageType = "StartScanning"
	// MessageTypeStopAllDevices is the type string for a [StopAllDevicesMessage].
	MessageTypeStopAllDevices MessageType = "StopAllDevices"
	// MessageTypeStopDeviceCmd is the type string for a [StopDeviceCmdMessage].
	MessageTypeStopDeviceCmd MessageType = "StopDeviceCmd"
	// MessageTypeStopScanning is the type string for a [StopScanningMessage].
	MessageTypeStopScanning MessageType = "StopScanning"
)

// Payload is a list of messages sent from the buttplug.io websocket server.
// Use this type to parse each message in the payload.
type Payload []Message

var (
	_ json.UnmarshalerFrom = (*Payload)(nil)
	_ json.MarshalerTo     = Payload(nil)
	_ slog.LogValuer       = Payload(nil)
)

// UnmarshalJSONFrom implements [json.UnmarshalerFrom].
// It consumes one full array of messages from the given JSON decoder.
func (p *Payload) UnmarshalJSONFrom(decoder *jsontext.Decoder) error {
	readTokenKind := func(need jsontext.Kind) error {
		t, err := decoder.ReadToken()
		if err != nil {
			return fmt.Errorf("failed to read token for %v: %w", need, err)
		}
		if t.Kind() != need {
			return fmt.Errorf("expected %v token, got %v", need, t)
		}
		return nil
	}

	for {
		// Advance reader into the array body.
		if err := readTokenKind(jsontext.Kind('[')); err != nil {
			return fmt.Errorf("failed to read start of array token: %w", err)
		}

		for {
			// Advance reader into message body.
			t, err := decoder.ReadToken()
			if err != nil {
				return fmt.Errorf("failed to read token: %w", err)
			}

			switch t.Kind() {
			case ']':
				// End of array, we're done.
				return nil
			case '{':
			// Start of object, continue processing.
			default:
				return fmt.Errorf("expected start of object or end of array, got %v", t.Kind())
			}

			var key string
			if err := json.UnmarshalDecode(decoder, &key); err != nil {
				return fmt.Errorf("failed to unmarshal message type key: %w", err)
			}

			switch MessageType(key) {
			case MessageTypeDeviceAdded:
				var msg DeviceAddedMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeDeviceList:
				var msg DeviceListMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeDeviceRemoved:
				var msg DeviceRemovedMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeError:
				var msg ErrorMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeLinearCmd:
				var msg LinearCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeOK:
				var msg OKMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypePing:
				var msg PingMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRawReadCmd:
				var msg RawReadCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRawReading:
				var msg RawReadingMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRawSubscribeCmd:
				var msg RawSubscribeCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRawUnsubscribeCmd:
				var msg RawUnsubscribeCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRawWriteCmd:
				var msg RawWriteCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRequestDeviceList:
				var msg RequestDeviceListMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRequestServerInfo:
				var msg RequestServerInfoMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRotateCmd:
				var msg RotateCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeScalarCmd:
				var msg ScalarCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeScanningFinished:
				var msg ScanningFinishedMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeSensorReadCmd:
				var msg SensorReadCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeSensorReading:
				var msg SensorReadingMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeSensorSubscribeCmd:
				var msg SensorSubscribeCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeSensorUnsubscribeCmd:
				var msg SensorUnsubscribeCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeServerInfo:
				var msg ServerInfoMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStartScanning:
				var msg StartScanningMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStopAllDevices:
				var msg StopAllDevicesMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStopDeviceCmd:
				var msg StopDeviceCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStopScanning:
				var msg StopScanningMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			default:
				v, err := decoder.ReadValue()
				if err != nil {
					return fmt.Errorf("failed to read unknown buttplug.io message type %q: %w", key, err)
				}
				slog.Warn(
					"received unknown buttplug.io message type, ignoring",
					slog.String("msg.type", key),
					slog.Any("msg.body", v))
			}

			// Advance reader out of the object body.
			if err = readTokenKind(jsontext.Kind('}')); err != nil {
				return fmt.Errorf("failed to read end of object token: %w", err)
			}
		}
	}
}

// MarshalJSONTo writes the payload as the JSON websocket wire protocol.
func (p Payload) MarshalJSONTo(encoder *jsontext.Encoder) error {
	if err := encoder.WriteToken(jsontext.BeginArray); err != nil {
		return fmt.Errorf("failed to write start of payload array token: %w", err)
	}

	for i, msg := range p {
		if err := encoder.WriteToken(jsontext.BeginObject); err != nil {
			return fmt.Errorf("failed to write start of message object token: %w", err)
		}

		if err := encoder.WriteToken(jsontext.String(string(msg.Type()))); err != nil {
			return fmt.Errorf("failed to write message type key token: %w", err)
		}

		if err := json.MarshalEncode(encoder, msg); err != nil {
			return fmt.Errorf("failed to marshal message[%d] (type %T): %w", i, msg, err)
		}

		if err := encoder.WriteToken(jsontext.EndObject); err != nil {
			return fmt.Errorf("failed to write end of message object token: %w", err)
		}
	}

	if err := encoder.WriteToken(jsontext.EndArray); err != nil {
		return fmt.Errorf("failed to write end of array token: %w", err)
	}

	return nil
}

// LogValue implements [slog.LogValuer].
func (p Payload) LogValue() slog.Value {
	attrs := make([]slog.Attr, len(p))
	for i, msg := range p {
		attrs[i] = slog.Any(fmt.Sprintf("payload[%d]", i), msg)
	}
	return slog.GroupValue(attrs...)
}

// Message represents a single message in the buttplug.io protocol.
//
// The following messages are defined:
//   - [DeviceAddedMessage]
//   - [DeviceListMessage]
//   - [DeviceRemovedMessage]
//   - [ErrorMessage]
//   - [LinearCmdMessage]
//   - [OKMessage]
//   - [PingMessage]
//   - [RawReadCmdMessage]
//   - [RawReadingMessage]
//   - [RawSubscribeCmdMessage]
//   - [RawUnsubscribeCmdMessage]
//   - [RawWriteCmdMessage]
//   - [RequestDeviceListMessage]
//   - [RequestServerInfoMessage]
//   - [RotateCmdMessage]
//   - [ScalarCmdMessage]
//   - [ScanningFinishedMessage]
//   - [SensorReadCmdMessage]
//   - [SensorReadingMessage]
//   - [SensorSubscribeCmdMessage]
//   - [SensorUnsubscribeCmdMessage]
//   - [ServerInfoMessage]
//   - [StartScanningMessage]
//   - [StopAllDevicesMessage]
//   - [StopDeviceCmdMessage]
//   - [StopScanningMessage]
type Message interface {
	// Type returns the message type of the message.
	Type() MessageType

	isMessage()
}

// ClientMessage represents a message that can be sent from the client to the server.
// It extends [Message] with a way to set the client ID to be used when sending the message.
//
// The following messages are defined:
//   - [DeviceListMessage]
//   - [LinearCmdMessage]
//   - [OKMessage]
//   - [PingMessage]
//   - [RawReadCmdMessage]
//   - [RawSubscribeCmdMessage]
//   - [RawUnsubscribeCmdMessage]
//   - [RawWriteCmdMessage]
//   - [RequestDeviceListMessage]
//   - [RequestServerInfoMessage]
//   - [RotateCmdMessage]
//   - [ScalarCmdMessage]
//   - [SensorReadCmdMessage]
//   - [SensorSubscribeCmdMessage]
//   - [SensorUnsubscribeCmdMessage]
//   - [ServerInfoMessage]
//   - [StartScanningMessage]
//   - [StopAllDevicesMessage]
//   - [StopDeviceCmdMessage]
//   - [StopScanningMessage]
type ClientMessage interface {
	Message
	// ClientID returns the ID field of the message.
	ClientID() ClientID
	// WithID sets the ID field of the shallow-copied message and returns the modified message.
	WithID(id ClientID) ClientMessage

	isClientMessage()
}

// ServerMessage represents a message that can be sent from the server to the client.
// It extends [Message].
//
// The following messages are defined:
//   - [ErrorMessage]
//   - [RawReadingMessage]
//   - [SensorReadingMessage]
type ServerMessage interface {
	Message
	// ServerID returns the ID field of the message.
	ServerID() ServerID

	isServerMessage()
}

// InternalMessage is a special type that the library uses for internal-only messages.
// Messages of this type were never emitted from the server.
type InternalMessage struct{}

func (i *InternalMessage) isMessage()         {}
func (i *InternalMessage) isInternalMessage() {}

// Type returns an empty string for internal messages.
func (m InternalMessage) Type() MessageType {
	return ""
}

// IsInternalMessage returns whether the message is an internal-only message.
func IsInternalMessage(m Message) bool {
	_, ok := m.(interface {
		isInternalMessage()
	})
	return ok
}

// MarshalJSON returns an error because internal messages cannot be marshaled.
func (m InternalMessage) MarshalJSON() ([]byte, error) {
	return nil, errors.New("internal messages cannot be marshaled")
}

// Type returns [MessageTypeDeviceAdded].
func (d *DeviceAddedMessage) Type() MessageType {
	return MessageTypeDeviceAdded
}

func (d *DeviceAddedMessage) isMessage() {}

// LogValue implements [slog.LogValuer].
func (d *DeviceAddedMessage) LogValue() slog.Value {
	type raw DeviceAddedMessage
	return slog.GroupValue(
		slog.String("type", "DeviceAdded"),
		slog.Any("data", (*raw)(d)))
}

// Type returns [MessageTypeDeviceList].
func (d *DeviceListMessage) Type() MessageType {
	return MessageTypeDeviceList
}

func (d *DeviceListMessage) isMessage()       {}
func (d *DeviceListMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (d *DeviceListMessage) ClientID() ClientID {
	return d.ID
}

// WithID implements [ClientMessage].
func (d *DeviceListMessage) WithID(id ClientID) ClientMessage {
	d.ID = id
	return d
}

// LogValue implements [slog.LogValuer].
func (d *DeviceListMessage) LogValue() slog.Value {
	type raw DeviceListMessage
	return slog.GroupValue(
		slog.String("type", "DeviceList"),
		slog.Any("data", (*raw)(d)))
}

// Type returns [MessageTypeDeviceRemoved].
func (d *DeviceRemovedMessage) Type() MessageType {
	return MessageTypeDeviceRemoved
}

func (d *DeviceRemovedMessage) isMessage() {}

// LogValue implements [slog.LogValuer].
func (d *DeviceRemovedMessage) LogValue() slog.Value {
	type raw DeviceRemovedMessage
	return slog.GroupValue(
		slog.String("type", "DeviceRemoved"),
		slog.Any("data", (*raw)(d)))
}

// Type returns [MessageTypeError].
func (e *ErrorMessage) Type() MessageType {
	return MessageTypeError
}

func (e *ErrorMessage) isMessage()       {}
func (e *ErrorMessage) isServerMessage() {}

// ServerID implements [ServerMessage]
func (e *ErrorMessage) ServerID() ServerID {
	return e.ID
}

// LogValue implements [slog.LogValuer].
func (e *ErrorMessage) LogValue() slog.Value {
	type raw ErrorMessage
	return slog.GroupValue(
		slog.String("type", "Error"),
		slog.Any("data", (*raw)(e)))
}

// Type returns [MessageTypeLinearCmd].
func (l *LinearCmdMessage) Type() MessageType {
	return MessageTypeLinearCmd
}

func (l *LinearCmdMessage) isMessage()       {}
func (l *LinearCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (l *LinearCmdMessage) ClientID() ClientID {
	return l.ID
}

// WithID implements [ClientMessage].
func (l *LinearCmdMessage) WithID(id ClientID) ClientMessage {
	l.ID = id
	return l
}

// LogValue implements [slog.LogValuer].
func (l *LinearCmdMessage) LogValue() slog.Value {
	type raw LinearCmdMessage
	return slog.GroupValue(
		slog.String("type", "LinearCmd"),
		slog.Any("data", (*raw)(l)))
}

// Type returns [MessageTypeOK].
func (o *OKMessage) Type() MessageType {
	return MessageTypeOK
}

func (o *OKMessage) isMessage()       {}
func (o *OKMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (o *OKMessage) ClientID() ClientID {
	return o.ID
}

// WithID implements [ClientMessage].
func (o *OKMessage) WithID(id ClientID) ClientMessage {
	o.ID = id
	return o
}

// LogValue implements [slog.LogValuer].
func (o *OKMessage) LogValue() slog.Value {
	type raw OKMessage
	return slog.GroupValue(
		slog.String("type", "Ok"),
		slog.Any("data", (*raw)(o)))
}

// Type returns [MessageTypePing].
func (p *PingMessage) Type() MessageType {
	return MessageTypePing
}

func (p *PingMessage) isMessage()       {}
func (p *PingMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (p *PingMessage) ClientID() ClientID {
	return p.ID
}

// WithID implements [ClientMessage].
func (p *PingMessage) WithID(id ClientID) ClientMessage {
	p.ID = id
	return p
}

// LogValue implements [slog.LogValuer].
func (p *PingMessage) LogValue() slog.Value {
	type raw PingMessage
	return slog.GroupValue(
		slog.String("type", "Ping"),
		slog.Any("data", (*raw)(p)))
}

// Type returns [MessageTypeRawReadCmd].
func (r *RawReadCmdMessage) Type() MessageType {
	return MessageTypeRawReadCmd
}

func (r *RawReadCmdMessage) isMessage()       {}
func (r *RawReadCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RawReadCmdMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RawReadCmdMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RawReadCmdMessage) LogValue() slog.Value {
	type raw RawReadCmdMessage
	return slog.GroupValue(
		slog.String("type", "RawReadCmd"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRawReading].
func (r *RawReadingMessage) Type() MessageType {
	return MessageTypeRawReading
}

func (r *RawReadingMessage) isMessage()       {}
func (r *RawReadingMessage) isServerMessage() {}

// ServerID implements [ServerMessage]
func (r *RawReadingMessage) ServerID() ServerID {
	return r.ID
}

// LogValue implements [slog.LogValuer].
func (r *RawReadingMessage) LogValue() slog.Value {
	type raw RawReadingMessage
	return slog.GroupValue(
		slog.String("type", "RawReading"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRawSubscribeCmd].
func (r *RawSubscribeCmdMessage) Type() MessageType {
	return MessageTypeRawSubscribeCmd
}

func (r *RawSubscribeCmdMessage) isMessage()       {}
func (r *RawSubscribeCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RawSubscribeCmdMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RawSubscribeCmdMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RawSubscribeCmdMessage) LogValue() slog.Value {
	type raw RawSubscribeCmdMessage
	return slog.GroupValue(
		slog.String("type", "RawSubscribeCmd"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRawUnsubscribeCmd].
func (r *RawUnsubscribeCmdMessage) Type() MessageType {
	return MessageTypeRawUnsubscribeCmd
}

func (r *RawUnsubscribeCmdMessage) isMessage()       {}
func (r *RawUnsubscribeCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RawUnsubscribeCmdMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RawUnsubscribeCmdMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RawUnsubscribeCmdMessage) LogValue() slog.Value {
	type raw RawUnsubscribeCmdMessage
	return slog.GroupValue(
		slog.String("type", "RawUnsubscribeCmd"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRawWriteCmd].
func (r *RawWriteCmdMessage) Type() MessageType {
	return MessageTypeRawWriteCmd
}

func (r *RawWriteCmdMessage) isMessage()       {}
func (r *RawWriteCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RawWriteCmdMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RawWriteCmdMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RawWriteCmdMessage) LogValue() slog.Value {
	type raw RawWriteCmdMessage
	return slog.GroupValue(
		slog.String("type", "RawWriteCmd"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRequestDeviceList].
func (r *RequestDeviceListMessage) Type() MessageType {
	return MessageTypeRequestDeviceList
}

func (r *RequestDeviceListMessage) isMessage()       {}
func (r *RequestDeviceListMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RequestDeviceListMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RequestDeviceListMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RequestDeviceListMessage) LogValue() slog.Value {
	type raw RequestDeviceListMessage
	return slog.GroupValue(
		slog.String("type", "RequestDeviceList"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRequestServerInfo].
func (r *RequestServerInfoMessage) Type() MessageType {
	return MessageTypeRequestServerInfo
}

func (r *RequestServerInfoMessage) isMessage()       {}
func (r *RequestServerInfoMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RequestServerInfoMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RequestServerInfoMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RequestServerInfoMessage) LogValue() slog.Value {
	type raw RequestServerInfoMessage
	return slog.GroupValue(
		slog.String("type", "RequestServerInfo"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRotateCmd].
func (r *RotateCmdMessage) Type() MessageType {
	return MessageTypeRotateCmd
}

func (r *RotateCmdMessage) isMessage()       {}
func (r *RotateCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RotateCmdMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RotateCmdMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RotateCmdMessage) LogValue() slog.Value {
	type raw RotateCmdMessage
	return slog.GroupValue(
		slog.String("type", "RotateCmd"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeScalarCmd].
func (s *ScalarCmdMessage) Type() MessageType {
	return MessageTypeScalarCmd
}

func (s *ScalarCmdMessage) isMessage()       {}
func (s *ScalarCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *ScalarCmdMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *ScalarCmdMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *ScalarCmdMessage) LogValue() slog.Value {
	type raw ScalarCmdMessage
	return slog.GroupValue(
		slog.String("type", "ScalarCmd"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeScanningFinished].
func (s *ScanningFinishedMessage) Type() MessageType {
	return MessageTypeScanningFinished
}

func (s *ScanningFinishedMessage) isMessage() {}

// LogValue implements [slog.LogValuer].
func (s *ScanningFinishedMessage) LogValue() slog.Value {
	type raw ScanningFinishedMessage
	return slog.GroupValue(
		slog.String("type", "ScanningFinished"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeSensorReadCmd].
func (s *SensorReadCmdMessage) Type() MessageType {
	return MessageTypeSensorReadCmd
}

func (s *SensorReadCmdMessage) isMessage()       {}
func (s *SensorReadCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *SensorReadCmdMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *SensorReadCmdMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *SensorReadCmdMessage) LogValue() slog.Value {
	type raw SensorReadCmdMessage
	return slog.GroupValue(
		slog.String("type", "SensorReadCmd"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeSensorReading].
func (s *SensorReadingMessage) Type() MessageType {
	return MessageTypeSensorReading
}

func (s *SensorReadingMessage) isMessage()       {}
func (s *SensorReadingMessage) isServerMessage() {}

// ServerID implements [ServerMessage]
func (s *SensorReadingMessage) ServerID() ServerID {
	return s.ID
}

// LogValue implements [slog.LogValuer].
func (s *SensorReadingMessage) LogValue() slog.Value {
	type raw SensorReadingMessage
	return slog.GroupValue(
		slog.String("type", "SensorReading"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeSensorSubscribeCmd].
func (s *SensorSubscribeCmdMessage) Type() MessageType {
	return MessageTypeSensorSubscribeCmd
}

func (s *SensorSubscribeCmdMessage) isMessage()       {}
func (s *SensorSubscribeCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *SensorSubscribeCmdMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *SensorSubscribeCmdMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *SensorSubscribeCmdMessage) LogValue() slog.Value {
	type raw SensorSubscribeCmdMessage
	return slog.GroupValue(
		slog.String("type", "SensorSubscribeCmd"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeSensorUnsubscribeCmd].
func (s *SensorUnsubscribeCmdMessage) Type() MessageType {
	return MessageTypeSensorUnsubscribeCmd
}

func (s *SensorUnsubscribeCmdMessage) isMessage()       {}
func (s *SensorUnsubscribeCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *SensorUnsubscribeCmdMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *SensorUnsubscribeCmdMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *SensorUnsubscribeCmdMessage) LogValue() slog.Value {
	type raw SensorUnsubscribeCmdMessage
	return slog.GroupValue(
		slog.String("type", "SensorUnsubscribeCmd"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeServerInfo].
func (s *ServerInfoMessage) Type() MessageType {
	return MessageTypeServerInfo
}

func (s *ServerInfoMessage) isMessage()       {}
func (s *ServerInfoMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *ServerInfoMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *ServerInfoMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *ServerInfoMessage) LogValue() slog.Value {
	type raw ServerInfoMessage
	return slog.GroupValue(
		slog.String("type", "ServerInfo"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStartScanning].
func (s *StartScanningMessage) Type() MessageType {
	return MessageTypeStartScanning
}

func (s *StartScanningMessage) isMessage()       {}
func (s *StartScanningMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StartScanningMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StartScanningMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StartScanningMessage) LogValue() slog.Value {
	type raw StartScanningMessage
	return slog.GroupValue(
		slog.String("type", "StartScanning"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStopAllDevices].
func (s *StopAllDevicesMessage) Type() MessageType {
	return MessageTypeStopAllDevices
}

func (s *StopAllDevicesMessage) isMessage()       {}
func (s *StopAllDevicesMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StopAllDevicesMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StopAllDevicesMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StopAllDevicesMessage) LogValue() slog.Value {
	type raw StopAllDevicesMessage
	return slog.GroupValue(
		slog.String("type", "StopAllDevices"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStopDeviceCmd].
func (s *StopDeviceCmdMessage) Type() MessageType {
	return MessageTypeStopDeviceCmd
}

func (s *StopDeviceCmdMessage) isMessage()       {}
func (s *StopDeviceCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StopDeviceCmdMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StopDeviceCmdMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StopDeviceCmdMessage) LogValue() slog.Value {
	type raw StopDeviceCmdMessage
	return slog.GroupValue(
		slog.String("type", "StopDeviceCmd"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStopScanning].
func (s *StopScanningMessage) Type() MessageType {
	return MessageTypeStopScanning
}

func (s *StopScanningMessage) isMessage()       {}
func (s *StopScanningMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StopScanningMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StopScanningMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StopScanningMessage) LogValue() slog.Value {
	type raw StopScanningMessage
	return slog.GroupValue(
		slog.String("type", "StopScanning"),
		slog.Any("data", (*raw)(s)))
}

// DeviceAddedMessage: notifies client that a device of a certain type has been
// added to the server.
type DeviceAddedMessage struct {
	// ID: used for non-direct-reply messages that can only be sent from server
	// to client, using the reserved system message Id of 0.
	ID SystemID `json:"Id"`
	// DeviceName: name of the device.
	DeviceName DeviceName `json:"DeviceName"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// DeviceMessages: a list of the messages a device will accept on this
	// server implementation.
	DeviceMessages         DeviceMessages       `json:"DeviceMessages"`
	DeviceDisplayName      ptr.Optional[string] `json:"DeviceDisplayName,omitzero"`
	DeviceMessageTimingGap ptr.Optional[int]    `json:"DeviceMessageTimingGap,omitzero"`
}

// DeviceListMessage: list of all available devices known to the system.
type DeviceListMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// Devices: array of device ids and names.
	Devices []Device `json:"Devices"`
}

// DeviceRemovedMessage: notifies client that a device of a certain type has
// been removed from the server.
type DeviceRemovedMessage struct {
	// ID: used for non-direct-reply messages that can only be sent from server
	// to client, using the reserved system message Id of 0.
	ID SystemID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
}

// ErrorMessage: signifies the server encountered an error while processing the
// message indicated by the id.
type ErrorMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID           ServerID `json:"Id"`
	ErrorMessage string   `json:"ErrorMessage"`
	ErrorCode    float64  `json:"ErrorCode"`
}

// LinearCmdMessage: sends a linear movement command to a device that supports
// linear movements.
type LinearCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Vectors: device linear movement times (milliseconds) and positions
	// (floating point, 0 < x < 1) keyed on linear actuator number, stepping
	// will be device specific.
	Vectors []Vector `json:"Vectors"`
}

// OKMessage: signifies successful processing of the message indicated by the
// id.
type OKMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// PingMessage: connection keep-alive message.
type PingMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// RawReadCmdMessage: request a raw byte array from a device. Should only be
// used for testing/development.
type RawReadCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// Endpoint (from device config file) from which the data was retrieved.
	Endpoint string `json:"Endpoint"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Length: amount of data to read from device, 0 to exhaust whatever is in
	// immediate buffer.
	Length int `json:"Length"`
	// WaitForData: if true, then wait until Length amount of data is available.
	WaitForData bool `json:"WaitForData"`
}

// RawReadingMessage: raw byte array received from a device. Should only be used
// for testing/development.
type RawReadingMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ServerID `json:"Id"`
	// Endpoint (from device config file) from which the data was retrieved.
	Endpoint string `json:"Endpoint"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Data: raw byte string received from device.
	Data []int `json:"Data"`
}

// RawSubscribeCmdMessage: subscribe to an endpoint on a device to receive raw
// info back.
type RawSubscribeCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// Endpoint (from device config file) from which the data was retrieved.
	Endpoint string `json:"Endpoint"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
}

// RawUnsubscribeCmdMessage: unsubscribe to an endpoint on a device.
type RawUnsubscribeCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// Endpoint (from device config file) from which the data was retrieved.
	Endpoint string `json:"Endpoint"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
}

// RawWriteCmdMessage: sends a raw byte array to a device. Should only be used
// for testing/development.
type RawWriteCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// Endpoint (from device config file) to send command to.
	Endpoint string `json:"Endpoint"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Data: raw byte string to send to device.
	Data []int `json:"Data"`
	// WriteWithResponse: if true, BLE writes will use WriteWithResponse.
	// Value ignored for all other types.
	WriteWithResponse bool `json:"WriteWithResponse"`
}

// RequestDeviceListMessage: request for the server to send a list of devices to
// the client.
type RequestDeviceListMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// RequestServerInfoMessage: request server version, and relay client name.
type RequestServerInfoMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// ClientName: name of the client software.
	ClientName string `json:"ClientName"`
	// MessageVersion: message template version of the client software.
	MessageVersion int `json:"MessageVersion"`
}

// RotateCmdMessage: sends a rotate command to a device that supports rotation.
type RotateCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Rotations: device rotation speeds (floating point, 0 < x < 1) keyed on
	// rotator number, stepping will be device specific.
	Rotations []Rotation `json:"Rotations"`
}

// ScalarCmdMessage: sends a generic scalar command to a device.
type ScalarCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Scalars: device actution scalar (floating point, range can vary) keyed on
	// acutator index, stepping will be device specific.
	Scalars []Scalar `json:"Scalars"`
}

// ScanningFinishedMessage: server notification to client that scanning has
// ended.
type ScanningFinishedMessage struct {
	// ID: used for non-direct-reply messages that can only be sent from server
	// to client, using the reserved system message Id of 0.
	ID SystemID `json:"Id"`
}

// SensorReadCmdMessage: sends a request to read a sensor value.
type SensorReadCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	SensorIndex int         `json:"SensorIndex"`
	SensorType  string      `json:"SensorType"`
}

// SensorReadingMessage: returns from either a sensor read request or a
// subscribed sensor event.
type SensorReadingMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ServerID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	SensorIndex int         `json:"SensorIndex"`
	SensorType  string      `json:"SensorType"`
	Data        []int       `json:"Data"`
}

// SensorSubscribeCmdMessage: sends a request to subscribe for updates to a
// sensor value.
type SensorSubscribeCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	SensorIndex int         `json:"SensorIndex"`
	SensorType  string      `json:"SensorType"`
}

// SensorUnsubscribeCmdMessage: sends a request to subscribe for updates to a
// sensor value.
type SensorUnsubscribeCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	SensorIndex int         `json:"SensorIndex"`
	SensorType  string      `json:"SensorType"`
}

// ServerInfoMessage: server version information, in Major.Minor.Build format.
type ServerInfoMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// MessageVersion: message template version of the server software.
	MessageVersion int `json:"MessageVersion"`
	// MaxPingTime: maximum time (in milliseconds) the server will wait between
	// ping messages from client before shutting down.
	MaxPingTime int `json:"MaxPingTime"`
	// ServerName: name of the server. Can be 0-length.
	ServerName string `json:"ServerName"`
}

// StartScanningMessage: request for the server to start scanning for new
// devices.
type StartScanningMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// StopAllDevicesMessage: stops all actions currently being taken by all
// connected devices.
type StopAllDevicesMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// StopDeviceCmdMessage: stops the all actions currently being taken by a
// device.
type StopDeviceCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
}

// StopScanningMessage: request for the server to stop scanning for new devices.
type StopScanningMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// SystemID: used for non-direct-reply messages that can only be sent from
// server to client, using the reserved system message Id of 0.
type SystemID int

// DeviceName: name of the device.
type DeviceName string

// DeviceIndex: index used for referencing the device in device messages.
type DeviceIndex int

// DeviceMessages: a list of the messages a device will accept on this server
// implementation.
type DeviceMessages struct {
	LinearCmd []LinearCmd `json:"LinearCmd,omitzero"`
	// RawReadCmd: attributes for raw device messages.
	RawReadCmd ptr.Optional[RawMessageAttributes] `json:"RawReadCmd,omitzero"`
	// RawSubscribeCmd: attributes for raw device messages.
	RawSubscribeCmd ptr.Optional[RawMessageAttributes] `json:"RawSubscribeCmd,omitzero"`
	// RawWriteCmd: attributes for raw device messages.
	RawWriteCmd        ptr.Optional[RawMessageAttributes] `json:"RawWriteCmd,omitzero"`
	RotateCmd          []RotateCmd                        `json:"RotateCmd,omitzero"`
	ScalarCmd          []ScalarCmd                        `json:"ScalarCmd,omitzero"`
	SensorReadCmd      []SensorReadCmdItem                `json:"SensorReadCmd,omitzero"`
	SensorSubscribeCmd []SensorSubscribeCmdItem           `json:"SensorSubscribeCmd,omitzero"`
	// StopDeviceCmd: attributes for device message that have no attributes.
	StopDeviceCmd ptr.Optional[NullMessageAttributes] `json:"StopDeviceCmd,omitzero"`
}

// ClientID: user-set id for the message. 0 denotes system message and is
// reserved.
type ClientID int

type Device struct {
	// DeviceName: name of the device.
	DeviceName DeviceName `json:"DeviceName"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// DeviceMessages: a list of the messages a device will accept on this
	// server implementation.
	DeviceMessages         DeviceMessages       `json:"DeviceMessages"`
	DeviceDisplayName      ptr.Optional[string] `json:"DeviceDisplayName,omitzero"`
	DeviceMessageTimingGap ptr.Optional[int]    `json:"DeviceMessageTimingGap,omitzero"`
}

// ServerID: user-set id for the message. 0 denotes system message and is
// reserved.
type ServerID int

type Vector struct {
	// Index: linear actuator number.
	Index int `json:"Index"`
	// Duration: linear movement time in milliseconds.
	Duration float64 `json:"Duration"`
	// Position: linear movement position (floating point, 0 < x < 1), stepping
	// will be device specific.
	Position float64 `json:"Position"`
}

type Rotation struct {
	// Index: rotator number.
	Index int `json:"Index"`
	// Speed: rotation speed (floating point, 0 < x < 1), stepping will be
	// device specific.
	Speed float64 `json:"Speed"`
	// Clockwise: rotation direction (boolean). Not all devices have a concept
	// of actual clockwise.
	Clockwise bool `json:"Clockwise"`
}

type Scalar struct {
	// Index: actuator index.
	Index int `json:"Index"`
	// Scalar: actuator scalar (floating point, range can vary), stepping will
	// be device specific.
	Scalar float64 `json:"Scalar"`
	// ActuatorType: actuator type that is expected to be controlled with this
	// subcommand.
	ActuatorType string `json:"ActuatorType"`
}

// LinearCmd: attributes for device messages.
type LinearCmd struct {
	// ActuatorType: denotes type of actuator (Vibrator, Linear, Oscillator,
	// etc...).
	ActuatorType      ptr.Optional[string] `json:"ActuatorType,omitzero"`
	FeatureDescriptor ptr.Optional[string] `json:"FeatureDescriptor,omitzero"`
	// StepCount: specifies granularity of each feature on the device.
	StepCount ptr.Optional[StepCount] `json:"StepCount,omitzero"`
}

// RawMessageAttributes: attributes for raw device messages.
type RawMessageAttributes struct {
	Endpoints []string `json:"Endpoints,omitzero"`
}

// RotateCmd: attributes for device messages.
type RotateCmd struct {
	// ActuatorType: denotes type of actuator (Vibrator, Linear, Oscillator,
	// etc...).
	ActuatorType      ptr.Optional[string] `json:"ActuatorType,omitzero"`
	FeatureDescriptor ptr.Optional[string] `json:"FeatureDescriptor,omitzero"`
	// StepCount: specifies granularity of each feature on the device.
	StepCount ptr.Optional[StepCount] `json:"StepCount,omitzero"`
}

// ScalarCmd: attributes for device messages.
type ScalarCmd struct {
	// ActuatorType: denotes type of actuator (Vibrator, Linear, Oscillator,
	// etc...).
	ActuatorType      ptr.Optional[string] `json:"ActuatorType,omitzero"`
	FeatureDescriptor ptr.Optional[string] `json:"FeatureDescriptor,omitzero"`
	// StepCount: specifies granularity of each feature on the device.
	StepCount ptr.Optional[StepCount] `json:"StepCount,omitzero"`
}

// SensorReadCmdItem: attributes for sensor device messages.
type SensorReadCmdItem struct {
	SensorType        string   `json:"SensorType"`
	FeatureDescriptor string   `json:"FeatureDescriptor"`
	SensorRange       [][2]int `json:"SensorRange"`
}

// SensorSubscribeCmdItem: attributes for sensor device messages.
type SensorSubscribeCmdItem struct {
	SensorType        string   `json:"SensorType"`
	FeatureDescriptor string   `json:"FeatureDescriptor"`
	SensorRange       [][2]int `json:"SensorRange"`
}

// NullMessageAttributes: attributes for device message that have no attributes.
type NullMessageAttributes struct{}

// StepCount: specifies granularity of each feature on the device.
type StepCount int
