// Code generated by buttplug-generate; DO NOT EDIT.

// Package schema contains the Buttplug message schema for version 4.
package schema

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"libdb.so/go-buttplug/schema/ptr"
	"log/slog"
)

// MessageType is the type string used to identify a buttplug.io message from the wire.
type MessageType string

// All defined message types.
const (
	// MessageTypeDeviceList is the type string for a [DeviceListMessage].
	MessageTypeDeviceList MessageType = "DeviceList"
	// MessageTypeError is the type string for a [ErrorMessage].
	MessageTypeError MessageType = "Error"
	// MessageTypeInputCmd is the type string for a [InputCmdMessage].
	MessageTypeInputCmd MessageType = "InputCmd"
	// MessageTypeInputReading is the type string for a [InputReadingMessage].
	MessageTypeInputReading MessageType = "InputReading"
	// MessageTypeOK is the type string for a [OKMessage].
	MessageTypeOK MessageType = "Ok"
	// MessageTypeOutputCmd is the type string for a [OutputCmdMessage].
	MessageTypeOutputCmd MessageType = "OutputCmd"
	// MessageTypePing is the type string for a [PingMessage].
	MessageTypePing MessageType = "Ping"
	// MessageTypeRequestDeviceList is the type string for a [RequestDeviceListMessage].
	MessageTypeRequestDeviceList MessageType = "RequestDeviceList"
	// MessageTypeRequestServerInfo is the type string for a [RequestServerInfoMessage].
	MessageTypeRequestServerInfo MessageType = "RequestServerInfo"
	// MessageTypeScanningFinished is the type string for a [ScanningFinishedMessage].
	MessageTypeScanningFinished MessageType = "ScanningFinished"
	// MessageTypeServerInfo is the type string for a [ServerInfoMessage].
	MessageTypeServerInfo MessageType = "ServerInfo"
	// MessageTypeStartScanning is the type string for a [StartScanningMessage].
	MessageTypeStartScanning MessageType = "StartScanning"
	// MessageTypeStopAllDevices is the type string for a [StopAllDevicesMessage].
	MessageTypeStopAllDevices MessageType = "StopAllDevices"
	// MessageTypeStopDeviceCmd is the type string for a [StopDeviceCmdMessage].
	MessageTypeStopDeviceCmd MessageType = "StopDeviceCmd"
	// MessageTypeStopScanning is the type string for a [StopScanningMessage].
	MessageTypeStopScanning MessageType = "StopScanning"
)

// Payload is a list of messages sent from the buttplug.io websocket server.
// Use this type to parse each message in the payload.
type Payload []Message

var (
	_ json.UnmarshalerFrom = (*Payload)(nil)
	_ json.MarshalerTo     = Payload(nil)
	_ slog.LogValuer       = Payload(nil)
)

// UnmarshalJSONFrom implements [json.UnmarshalerFrom].
// It consumes one full array of messages from the given JSON decoder.
func (p *Payload) UnmarshalJSONFrom(decoder *jsontext.Decoder) error {
	readTokenKind := func(need jsontext.Kind) error {
		t, err := decoder.ReadToken()
		if err != nil {
			return fmt.Errorf("failed to read token for %v: %w", need, err)
		}
		if t.Kind() != need {
			return fmt.Errorf("expected %v token, got %v", need, t)
		}
		return nil
	}

	for {
		// Advance reader into the array body.
		if err := readTokenKind(jsontext.Kind('[')); err != nil {
			return fmt.Errorf("failed to read start of array token: %w", err)
		}

		for {
			// Advance reader into message body.
			t, err := decoder.ReadToken()
			if err != nil {
				return fmt.Errorf("failed to read token: %w", err)
			}

			switch t.Kind() {
			case ']':
				// End of array, we're done.
				return nil
			case '{':
			// Start of object, continue processing.
			default:
				return fmt.Errorf("expected start of object or end of array, got %v", t.Kind())
			}

			var key string
			if err := json.UnmarshalDecode(decoder, &key); err != nil {
				return fmt.Errorf("failed to unmarshal message type key: %w", err)
			}

			switch MessageType(key) {
			case MessageTypeDeviceList:
				var msg DeviceListMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeError:
				var msg ErrorMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeInputCmd:
				var msg InputCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeInputReading:
				var msg InputReadingMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeOK:
				var msg OKMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeOutputCmd:
				var msg OutputCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypePing:
				var msg PingMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRequestDeviceList:
				var msg RequestDeviceListMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRequestServerInfo:
				var msg RequestServerInfoMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeScanningFinished:
				var msg ScanningFinishedMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeServerInfo:
				var msg ServerInfoMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStartScanning:
				var msg StartScanningMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStopAllDevices:
				var msg StopAllDevicesMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStopDeviceCmd:
				var msg StopDeviceCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStopScanning:
				var msg StopScanningMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			default:
				v, err := decoder.ReadValue()
				if err != nil {
					return fmt.Errorf("failed to read unknown buttplug.io message type %q: %w", key, err)
				}
				slog.Warn(
					"received unknown buttplug.io message type, ignoring",
					slog.String("msg.type", key),
					slog.Any("msg.body", v))
			}

			// Advance reader out of the object body.
			if err = readTokenKind(jsontext.Kind('}')); err != nil {
				return fmt.Errorf("failed to read end of object token: %w", err)
			}
		}
	}
}

// MarshalJSONTo writes the payload as the JSON websocket wire protocol.
func (p Payload) MarshalJSONTo(encoder *jsontext.Encoder) error {
	if err := encoder.WriteToken(jsontext.BeginArray); err != nil {
		return fmt.Errorf("failed to write start of payload array token: %w", err)
	}

	for i, msg := range p {
		if err := encoder.WriteToken(jsontext.BeginObject); err != nil {
			return fmt.Errorf("failed to write start of message object token: %w", err)
		}

		if err := encoder.WriteToken(jsontext.String(string(msg.Type()))); err != nil {
			return fmt.Errorf("failed to write message type key token: %w", err)
		}

		if err := json.MarshalEncode(encoder, msg); err != nil {
			return fmt.Errorf("failed to marshal message[%d] (type %T): %w", i, msg, err)
		}

		if err := encoder.WriteToken(jsontext.EndObject); err != nil {
			return fmt.Errorf("failed to write end of message object token: %w", err)
		}
	}

	if err := encoder.WriteToken(jsontext.EndArray); err != nil {
		return fmt.Errorf("failed to write end of array token: %w", err)
	}

	return nil
}

// LogValue implements [slog.LogValuer].
func (p Payload) LogValue() slog.Value {
	attrs := make([]slog.Attr, len(p))
	for i, msg := range p {
		attrs[i] = slog.Any(fmt.Sprintf("payload[%d]", i), msg)
	}
	return slog.GroupValue(attrs...)
}

// Message represents a single message in the buttplug.io protocol.
//
// The following messages are defined:
//   - [DeviceListMessage]
//   - [ErrorMessage]
//   - [InputCmdMessage]
//   - [InputReadingMessage]
//   - [OKMessage]
//   - [OutputCmdMessage]
//   - [PingMessage]
//   - [RequestDeviceListMessage]
//   - [RequestServerInfoMessage]
//   - [ScanningFinishedMessage]
//   - [ServerInfoMessage]
//   - [StartScanningMessage]
//   - [StopAllDevicesMessage]
//   - [StopDeviceCmdMessage]
//   - [StopScanningMessage]
type Message interface {
	// Type returns the message type of the message.
	Type() MessageType

	isMessage()
}

// ClientMessage represents a message that can be sent from the client to the server.
// It extends [Message] with a way to set the client ID to be used when sending the message.
//
// The following messages are defined:
//   - [InputCmdMessage]
//   - [OKMessage]
//   - [OutputCmdMessage]
//   - [PingMessage]
//   - [RequestDeviceListMessage]
//   - [RequestServerInfoMessage]
//   - [StartScanningMessage]
//   - [StopAllDevicesMessage]
//   - [StopDeviceCmdMessage]
//   - [StopScanningMessage]
type ClientMessage interface {
	Message
	// ClientID returns the ID field of the message.
	ClientID() ClientID
	// WithID sets the ID field of the shallow-copied message and returns the modified message.
	WithID(id ClientID) ClientMessage

	isClientMessage()
}

// ServerMessage represents a message that can be sent from the server to the client.
// It extends [Message].
//
// The following messages are defined:
//   - [DeviceListMessage]
//   - [ErrorMessage]
//   - [InputReadingMessage]
type ServerMessage interface {
	Message
	// ServerID returns the ID field of the message.
	ServerID() ServerID

	isServerMessage()
}

// InternalMessage is a special type that the library uses for internal-only messages.
// Messages of this type were never emitted from the server.
type InternalMessage struct{}

func (i *InternalMessage) isMessage()         {}
func (i *InternalMessage) isInternalMessage() {}

// Type returns an empty string for internal messages.
func (m InternalMessage) Type() MessageType {
	return ""
}

// IsInternalMessage returns whether the message is an internal-only message.
func IsInternalMessage(m Message) bool {
	_, ok := m.(interface {
		isInternalMessage()
	})
	return ok
}

// MarshalJSON returns an error because internal messages cannot be marshaled.
func (m InternalMessage) MarshalJSON() ([]byte, error) {
	return nil, errors.New("internal messages cannot be marshaled")
}

// Type returns [MessageTypeDeviceList].
func (d *DeviceListMessage) Type() MessageType {
	return MessageTypeDeviceList
}

func (d *DeviceListMessage) isMessage()       {}
func (d *DeviceListMessage) isServerMessage() {}

// ServerID implements [ServerMessage]
func (d *DeviceListMessage) ServerID() ServerID {
	return d.ID
}

// LogValue implements [slog.LogValuer].
func (d *DeviceListMessage) LogValue() slog.Value {
	type raw DeviceListMessage
	return slog.GroupValue(
		slog.String("type", "DeviceList"),
		slog.Any("data", (*raw)(d)))
}

// Type returns [MessageTypeError].
func (e *ErrorMessage) Type() MessageType {
	return MessageTypeError
}

func (e *ErrorMessage) isMessage()       {}
func (e *ErrorMessage) isServerMessage() {}

// ServerID implements [ServerMessage]
func (e *ErrorMessage) ServerID() ServerID {
	return e.ID
}

// LogValue implements [slog.LogValuer].
func (e *ErrorMessage) LogValue() slog.Value {
	type raw ErrorMessage
	return slog.GroupValue(
		slog.String("type", "Error"),
		slog.Any("data", (*raw)(e)))
}

// Type returns [MessageTypeInputCmd].
func (i *InputCmdMessage) Type() MessageType {
	return MessageTypeInputCmd
}

func (i *InputCmdMessage) isMessage()       {}
func (i *InputCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (i *InputCmdMessage) ClientID() ClientID {
	return i.ID
}

// WithID implements [ClientMessage].
func (i *InputCmdMessage) WithID(id ClientID) ClientMessage {
	i.ID = id
	return i
}

// LogValue implements [slog.LogValuer].
func (i *InputCmdMessage) LogValue() slog.Value {
	type raw InputCmdMessage
	return slog.GroupValue(
		slog.String("type", "InputCmd"),
		slog.Any("data", (*raw)(i)))
}

// Type returns [MessageTypeInputReading].
func (i *InputReadingMessage) Type() MessageType {
	return MessageTypeInputReading
}

func (i *InputReadingMessage) isMessage()       {}
func (i *InputReadingMessage) isServerMessage() {}

// ServerID implements [ServerMessage]
func (i *InputReadingMessage) ServerID() ServerID {
	return i.ID
}

// LogValue implements [slog.LogValuer].
func (i *InputReadingMessage) LogValue() slog.Value {
	type raw InputReadingMessage
	return slog.GroupValue(
		slog.String("type", "InputReading"),
		slog.Any("data", (*raw)(i)))
}

// Type returns [MessageTypeOK].
func (o *OKMessage) Type() MessageType {
	return MessageTypeOK
}

func (o *OKMessage) isMessage()       {}
func (o *OKMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (o *OKMessage) ClientID() ClientID {
	return o.ID
}

// WithID implements [ClientMessage].
func (o *OKMessage) WithID(id ClientID) ClientMessage {
	o.ID = id
	return o
}

// LogValue implements [slog.LogValuer].
func (o *OKMessage) LogValue() slog.Value {
	type raw OKMessage
	return slog.GroupValue(
		slog.String("type", "Ok"),
		slog.Any("data", (*raw)(o)))
}

// Type returns [MessageTypeOutputCmd].
func (o *OutputCmdMessage) Type() MessageType {
	return MessageTypeOutputCmd
}

func (o *OutputCmdMessage) isMessage()       {}
func (o *OutputCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (o *OutputCmdMessage) ClientID() ClientID {
	return o.ID
}

// WithID implements [ClientMessage].
func (o *OutputCmdMessage) WithID(id ClientID) ClientMessage {
	o.ID = id
	return o
}

// LogValue implements [slog.LogValuer].
func (o *OutputCmdMessage) LogValue() slog.Value {
	type raw OutputCmdMessage
	return slog.GroupValue(
		slog.String("type", "OutputCmd"),
		slog.Any("data", (*raw)(o)))
}

// Type returns [MessageTypePing].
func (p *PingMessage) Type() MessageType {
	return MessageTypePing
}

func (p *PingMessage) isMessage()       {}
func (p *PingMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (p *PingMessage) ClientID() ClientID {
	return p.ID
}

// WithID implements [ClientMessage].
func (p *PingMessage) WithID(id ClientID) ClientMessage {
	p.ID = id
	return p
}

// LogValue implements [slog.LogValuer].
func (p *PingMessage) LogValue() slog.Value {
	type raw PingMessage
	return slog.GroupValue(
		slog.String("type", "Ping"),
		slog.Any("data", (*raw)(p)))
}

// Type returns [MessageTypeRequestDeviceList].
func (r *RequestDeviceListMessage) Type() MessageType {
	return MessageTypeRequestDeviceList
}

func (r *RequestDeviceListMessage) isMessage()       {}
func (r *RequestDeviceListMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RequestDeviceListMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RequestDeviceListMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RequestDeviceListMessage) LogValue() slog.Value {
	type raw RequestDeviceListMessage
	return slog.GroupValue(
		slog.String("type", "RequestDeviceList"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRequestServerInfo].
func (r *RequestServerInfoMessage) Type() MessageType {
	return MessageTypeRequestServerInfo
}

func (r *RequestServerInfoMessage) isMessage()       {}
func (r *RequestServerInfoMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RequestServerInfoMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RequestServerInfoMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RequestServerInfoMessage) LogValue() slog.Value {
	type raw RequestServerInfoMessage
	return slog.GroupValue(
		slog.String("type", "RequestServerInfo"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeScanningFinished].
func (s *ScanningFinishedMessage) Type() MessageType {
	return MessageTypeScanningFinished
}

func (s *ScanningFinishedMessage) isMessage() {}

// LogValue implements [slog.LogValuer].
func (s *ScanningFinishedMessage) LogValue() slog.Value {
	type raw ScanningFinishedMessage
	return slog.GroupValue(
		slog.String("type", "ScanningFinished"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeServerInfo].
func (s *ServerInfoMessage) Type() MessageType {
	return MessageTypeServerInfo
}

func (s *ServerInfoMessage) isMessage() {}

// LogValue implements [slog.LogValuer].
func (s *ServerInfoMessage) LogValue() slog.Value {
	type raw ServerInfoMessage
	return slog.GroupValue(
		slog.String("type", "ServerInfo"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStartScanning].
func (s *StartScanningMessage) Type() MessageType {
	return MessageTypeStartScanning
}

func (s *StartScanningMessage) isMessage()       {}
func (s *StartScanningMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StartScanningMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StartScanningMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StartScanningMessage) LogValue() slog.Value {
	type raw StartScanningMessage
	return slog.GroupValue(
		slog.String("type", "StartScanning"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStopAllDevices].
func (s *StopAllDevicesMessage) Type() MessageType {
	return MessageTypeStopAllDevices
}

func (s *StopAllDevicesMessage) isMessage()       {}
func (s *StopAllDevicesMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StopAllDevicesMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StopAllDevicesMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StopAllDevicesMessage) LogValue() slog.Value {
	type raw StopAllDevicesMessage
	return slog.GroupValue(
		slog.String("type", "StopAllDevices"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStopDeviceCmd].
func (s *StopDeviceCmdMessage) Type() MessageType {
	return MessageTypeStopDeviceCmd
}

func (s *StopDeviceCmdMessage) isMessage()       {}
func (s *StopDeviceCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StopDeviceCmdMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StopDeviceCmdMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StopDeviceCmdMessage) LogValue() slog.Value {
	type raw StopDeviceCmdMessage
	return slog.GroupValue(
		slog.String("type", "StopDeviceCmd"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStopScanning].
func (s *StopScanningMessage) Type() MessageType {
	return MessageTypeStopScanning
}

func (s *StopScanningMessage) isMessage()       {}
func (s *StopScanningMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StopScanningMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StopScanningMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StopScanningMessage) LogValue() slog.Value {
	type raw StopScanningMessage
	return slog.GroupValue(
		slog.String("type", "StopScanning"),
		slog.Any("data", (*raw)(s)))
}

// DeviceListMessage: list of all available devices known to the system.
type DeviceListMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ServerID `json:"Id"`
	// Devices: array of device ids and names.
	Devices DeviceListMessageDevices `json:"Devices"`
}

// ErrorMessage: signifies the server encountered an error while processing the
// message indicated by the id.
type ErrorMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID           ServerID `json:"Id"`
	ErrorMessage string   `json:"ErrorMessage"`
	ErrorCode    float64  `json:"ErrorCode"`
}

// InputCmdMessage: sends a request to read a sensor value.
type InputCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex  DeviceIndex `json:"DeviceIndex"`
	FeatureIndex int         `json:"FeatureIndex"`
	InputType    string      `json:"InputType"`
	InputCommand string      `json:"InputCommand"`
}

// InputReadingMessage: returns from either a sensor read request or a
// subscribed sensor event.
type InputReadingMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ServerID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex  DeviceIndex             `json:"DeviceIndex"`
	FeatureIndex int                     `json:"FeatureIndex"`
	Data         InputReadingMessageData `json:"Data"`
}

// OKMessage: signifies successful processing of the message indicated by the
// id.
type OKMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// OutputCmdMessage: sends a generic value set command to a device.
type OutputCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// FeatureIndex: index used for referencing the device in device messages.
	FeatureIndex DeviceIndex   `json:"FeatureIndex"`
	Command      OutputCommand `json:"Command"`
}

// PingMessage: connection keep-alive message.
type PingMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// RequestDeviceListMessage: request for the server to send a list of devices to
// the client.
type RequestDeviceListMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// RequestServerInfoMessage: request server version, and relay client name.
type RequestServerInfoMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// ClientName: name of the client software.
	ClientName string `json:"ClientName"`
	// ProtocolVersionMajor: message template version of the server software.
	ProtocolVersionMajor int `json:"ProtocolVersionMajor"`
	// ProtocolVersionMinor: message template version of the server software.
	ProtocolVersionMinor int `json:"ProtocolVersionMinor"`
}

// ScanningFinishedMessage: server notification to client that scanning has
// ended.
type ScanningFinishedMessage struct {
	// ID: used for non-direct-reply messages that can only be sent from server
	// to client, using the reserved system message Id of 0.
	ID SystemID `json:"Id"`
}

// ServerInfoMessage: server version information, with API version in
// Major.Minor format.
type ServerInfoMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ptr.Optional[ClientID] `json:"Id,omitzero"`
	// MaxPingTime: maximum time (in milliseconds) the server will wait between
	// ping messages from client before shutting down.
	MaxPingTime ptr.Optional[int] `json:"MaxPingTime,omitzero"`
	// ProtocolVersionMajor: message template version of the server software.
	ProtocolVersionMajor ptr.Optional[int] `json:"ProtocolVersionMajor,omitzero"`
	// ProtocolVersionMinor: message template version of the server software.
	ProtocolVersionMinor ptr.Optional[int] `json:"ProtocolVersionMinor,omitzero"`
	// ServerName: name of the server. Can be 0-length.
	ServerName ptr.Optional[string] `json:"ServerName,omitzero"`
}

// StartScanningMessage: request for the server to start scanning for new
// devices.
type StartScanningMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// StopAllDevicesMessage: stops all actions currently being taken by all
// connected devices.
type StopAllDevicesMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// StopDeviceCmdMessage: stops the all actions currently being taken by a
// device.
type StopDeviceCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
}

// StopScanningMessage: request for the server to stop scanning for new devices.
type StopScanningMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// ServerID: user-set id for the message. 0 denotes system message and is
// reserved.
type ServerID int

// Devices: array of device ids and names.
type DeviceListMessageDevices map[int]DeviceListMessageDevicesValue

// DeviceListMessageDevicesValue: This is the properties map type for
// [DeviceListMessageDevices].
type DeviceListMessageDevicesValue struct {
	// DeviceName: name of the device.
	DeviceName DeviceName `json:"DeviceName"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex            DeviceIndex                                 `json:"DeviceIndex"`
	DeviceMessageTimingGap int                                         `json:"DeviceMessageTimingGap"`
	DeviceFeatures         DeviceListMessageDevicesValueDeviceFeatures `json:"DeviceFeatures"`
	DeviceDisplayName      ptr.Optional[string]                        `json:"DeviceDisplayName,omitzero"`
}

// ClientID: user-set id for the message. 0 denotes system message and is
// reserved.
type ClientID int

// DeviceIndex: index used for referencing the device in device messages.
type DeviceIndex int

// InputReadingMessageData: properties map for [InputReadingMessage.Data].
type InputReadingMessageData map[InputReadingMessageDataKey]int

// InputReadingMessageDataKey represents valid keys in [InputReadingMessageData].
type InputReadingMessageDataKey string

// Constants for valid keys in [InputReadingMessageData].
const (
	InputReadingMessageDataBattery  InputReadingMessageDataKey = "Battery"
	InputReadingMessageDataRSSI     InputReadingMessageDataKey = "Rssi"
	InputReadingMessageDataPressure InputReadingMessageDataKey = "Pressure"
	InputReadingMessageDataButton   InputReadingMessageDataKey = "Button"
)

// OutputCommand: properties map for [OutputCmdMessage.Command].
type OutputCommand map[OutputCommandKey]OutputCommandValueType

// OutputCommandKey represents valid keys in [OutputCommand].
type OutputCommandKey string

// Constants for valid keys in [OutputCommand].
const (
	OutputCommandVibrate              OutputCommandKey = "Vibrate"
	OutputCommandRotate               OutputCommandKey = "Rotate"
	OutputCommandOscillate            OutputCommandKey = "Oscillate"
	OutputCommandConstrict            OutputCommandKey = "Constrict"
	OutputCommandSpray                OutputCommandKey = "Spray"
	OutputCommandPosition             OutputCommandKey = "Position"
	OutputCommandTemperature          OutputCommandKey = "Temperature"
	OutputCommandLED                  OutputCommandKey = "Led"
	OutputCommandPositionWithDuration OutputCommandKey = "PositionWithDuration"
)

// OutputCommandValueType is a type that represents possible values of the map
// [OutputCommand].
//
// The following types can be used for this interface:
//   - [OutputCommandValue]
//   - [OutputCommandPositionWithDurationValue]
type OutputCommandValueType interface {
	outputCommandValueType()
}

// OutputCommandValue is the value matching pattern for [OutputCommandVibrate],
// [OutputCommandRotate], [OutputCommandOscillate], [OutputCommandConstrict],
// [OutputCommandSpray], [OutputCommandPosition], [OutputCommandTemperature] and
// [OutputCommandLED] of [OutputCommand].
type OutputCommandValue struct {
	Value float64 `json:"Value"`
}

// OutputCommandPositionWithDurationValue is the value matching pattern for
// [OutputCommandPositionWithDuration] of [OutputCommand].
type OutputCommandPositionWithDurationValue struct {
	Position float64 `json:"Position"`
	Duration float64 `json:"Duration"`
}

func (OutputCommandValue) outputCommandValueType()                     {}
func (OutputCommandPositionWithDurationValue) outputCommandValueType() {}

// SystemID: used for non-direct-reply messages that can only be sent from
// server to client, using the reserved system message Id of 0.
type SystemID int

// DeviceName: name of the device.
type DeviceName string

// DeviceListMessageDevicesValueDeviceFeatures: properties map for
// [DeviceListMessageDevicesValue.DeviceFeatures].
type DeviceListMessageDevicesValueDeviceFeatures map[int]DeviceFeature

// DeviceFeature: specifies feature for a device.
type DeviceFeature struct {
	FeatureDescription string                            `json:"FeatureDescription"`
	FeatureIndex       int                               `json:"FeatureIndex"`
	Input              ptr.Optional[DeviceFeatureInput]  `json:"Input,omitzero"`
	Output             ptr.Optional[DeviceFeatureOutput] `json:"Output,omitzero"`
}

// DeviceFeatureInput: properties map for [DeviceFeature.Input].
type DeviceFeatureInput map[string]DeviceFeatureInputValue

// DeviceFeatureInputValue: This is the properties map type for
// [DeviceFeatureInput].
type DeviceFeatureInputValue struct {
	ValueRange [][]int `json:"ValueRange"`
}

// DeviceFeatureOutput: properties map for [DeviceFeature.Output].
type DeviceFeatureOutput map[DeviceFeatureOutputKey]DeviceFeatureOutputValueType

// DeviceFeatureOutputKey represents valid keys in [DeviceFeatureOutput].
type DeviceFeatureOutputKey string

// Constants for valid keys in [DeviceFeatureOutput].
const (
	DeviceFeatureOutputPositionWithDuration DeviceFeatureOutputKey = "PositionWithDuration"
	DeviceFeatureOutputVibrate              DeviceFeatureOutputKey = "Vibrate"
	DeviceFeatureOutputRotate               DeviceFeatureOutputKey = "Rotate"
	DeviceFeatureOutputOscillate            DeviceFeatureOutputKey = "Oscillate"
	DeviceFeatureOutputConstrict            DeviceFeatureOutputKey = "Constrict"
	DeviceFeatureOutputSpray                DeviceFeatureOutputKey = "Spray"
	DeviceFeatureOutputPosition             DeviceFeatureOutputKey = "Position"
	DeviceFeatureOutputTemperature          DeviceFeatureOutputKey = "Temperature"
	DeviceFeatureOutputLED                  DeviceFeatureOutputKey = "Led"
)

// DeviceFeatureOutputValueType is a type that represents possible values of the
// map [DeviceFeatureOutput].
//
// The following types can be used for this interface:
//   - [DeviceFeatureOutputPositionWithDurationValue]
//   - [DeviceFeatureOutputValue]
type DeviceFeatureOutputValueType interface {
	deviceFeatureOutputValueType()
}

// DeviceFeatureOutputPositionWithDurationValue is the value matching pattern
// for [DeviceFeatureOutputPositionWithDuration] of [DeviceFeatureOutput].
type DeviceFeatureOutputPositionWithDurationValue struct {
	// Position: serialization of Rust's RangeInclusive Type.
	Position RangeInclusive `json:"Position"`
	// Duration: serialization of Rust's RangeInclusive Type.
	Duration RangeInclusive `json:"Duration"`
}

// DeviceFeatureOutputValue is the value matching pattern for
// [DeviceFeatureOutputVibrate], [DeviceFeatureOutputRotate],
// [DeviceFeatureOutputOscillate], [DeviceFeatureOutputConstrict],
// [DeviceFeatureOutputSpray], [DeviceFeatureOutputPosition],
// [DeviceFeatureOutputTemperature] and [DeviceFeatureOutputLED] of
// [DeviceFeatureOutput].
type DeviceFeatureOutputValue struct {
	// Value: serialization of Rust's RangeInclusive Type.
	Value RangeInclusive `json:"Value"`
}

func (DeviceFeatureOutputPositionWithDurationValue) deviceFeatureOutputValueType() {}
func (DeviceFeatureOutputValue) deviceFeatureOutputValueType()                     {}

// RangeInclusive: serialization of Rust's RangeInclusive Type.
type RangeInclusive [2]int
