// Code generated by buttplug-generate; DO NOT EDIT.

// Package schema contains the Buttplug message schema for version 1.
package schema

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"errors"
	"fmt"
	"libdb.so/go-buttplug/schema/ptr"
	"log/slog"
)

// MessageType is the type string used to identify a buttplug.io message from the wire.
type MessageType string

// All defined message types.
const (
	// MessageTypeDeviceAdded is the type string for a [DeviceAddedMessage].
	MessageTypeDeviceAdded MessageType = "DeviceAdded"
	// MessageTypeDeviceList is the type string for a [DeviceListMessage].
	MessageTypeDeviceList MessageType = "DeviceList"
	// MessageTypeDeviceRemoved is the type string for a [DeviceRemovedMessage].
	MessageTypeDeviceRemoved MessageType = "DeviceRemoved"
	// MessageTypeError is the type string for a [ErrorMessage].
	MessageTypeError MessageType = "Error"
	// MessageTypeFleshlightLaunchFW12Cmd is the type string for a [FleshlightLaunchFW12CmdMessage].
	MessageTypeFleshlightLaunchFW12Cmd MessageType = "FleshlightLaunchFW12Cmd"
	// MessageTypeKiirooCmd is the type string for a [KiirooCmdMessage].
	MessageTypeKiirooCmd MessageType = "KiirooCmd"
	// MessageTypeLinearCmd is the type string for a [LinearCmdMessage].
	MessageTypeLinearCmd MessageType = "LinearCmd"
	// MessageTypeLog is the type string for a [LogMessage].
	MessageTypeLog MessageType = "Log"
	// MessageTypeOK is the type string for a [OKMessage].
	MessageTypeOK MessageType = "Ok"
	// MessageTypePing is the type string for a [PingMessage].
	MessageTypePing MessageType = "Ping"
	// MessageTypeRequestDeviceList is the type string for a [RequestDeviceListMessage].
	MessageTypeRequestDeviceList MessageType = "RequestDeviceList"
	// MessageTypeRequestLog is the type string for a [RequestLogMessage].
	MessageTypeRequestLog MessageType = "RequestLog"
	// MessageTypeRequestServerInfo is the type string for a [RequestServerInfoMessage].
	MessageTypeRequestServerInfo MessageType = "RequestServerInfo"
	// MessageTypeRotateCmd is the type string for a [RotateCmdMessage].
	MessageTypeRotateCmd MessageType = "RotateCmd"
	// MessageTypeServerInfo is the type string for a [ServerInfoMessage].
	MessageTypeServerInfo MessageType = "ServerInfo"
	// MessageTypeStartScanning is the type string for a [StartScanningMessage].
	MessageTypeStartScanning MessageType = "StartScanning"
	// MessageTypeStopAllDevices is the type string for a [StopAllDevicesMessage].
	MessageTypeStopAllDevices MessageType = "StopAllDevices"
	// MessageTypeStopDeviceCmd is the type string for a [StopDeviceCmdMessage].
	MessageTypeStopDeviceCmd MessageType = "StopDeviceCmd"
	// MessageTypeStopScanning is the type string for a [StopScanningMessage].
	MessageTypeStopScanning MessageType = "StopScanning"
	// MessageTypeTest is the type string for a [TestMessage].
	MessageTypeTest MessageType = "Test"
	// MessageTypeVibrateCmd is the type string for a [VibrateCmdMessage].
	MessageTypeVibrateCmd MessageType = "VibrateCmd"
	// MessageTypeVorzeA10CycloneCmd is the type string for a [VorzeA10CycloneCmdMessage].
	MessageTypeVorzeA10CycloneCmd MessageType = "VorzeA10CycloneCmd"
)

// Payload is a list of messages sent from the buttplug.io websocket server.
// Use this type to parse each message in the payload.
type Payload []Message

var (
	_ json.UnmarshalerFrom = (*Payload)(nil)
	_ json.MarshalerTo     = Payload(nil)
	_ slog.LogValuer       = Payload(nil)
)

// UnmarshalJSONFrom implements [json.UnmarshalerFrom].
// It consumes one full array of messages from the given JSON decoder.
func (p *Payload) UnmarshalJSONFrom(decoder *jsontext.Decoder) error {
	readTokenKind := func(need jsontext.Kind) error {
		t, err := decoder.ReadToken()
		if err != nil {
			return fmt.Errorf("failed to read token for %v: %w", need, err)
		}
		if t.Kind() != need {
			return fmt.Errorf("expected %v token, got %v", need, t)
		}
		return nil
	}

	for {
		// Advance reader into the array body.
		if err := readTokenKind(jsontext.Kind('[')); err != nil {
			return fmt.Errorf("failed to read start of array token: %w", err)
		}

		for {
			// Advance reader into message body.
			t, err := decoder.ReadToken()
			if err != nil {
				return fmt.Errorf("failed to read token: %w", err)
			}

			switch t.Kind() {
			case ']':
				// End of array, we're done.
				return nil
			case '{':
			// Start of object, continue processing.
			default:
				return fmt.Errorf("expected start of object or end of array, got %v", t.Kind())
			}

			var key string
			if err := json.UnmarshalDecode(decoder, &key); err != nil {
				return fmt.Errorf("failed to unmarshal message type key: %w", err)
			}

			switch MessageType(key) {
			case MessageTypeDeviceAdded:
				var msg DeviceAddedMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeDeviceList:
				var msg DeviceListMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeDeviceRemoved:
				var msg DeviceRemovedMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeError:
				var msg ErrorMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeFleshlightLaunchFW12Cmd:
				var msg FleshlightLaunchFW12CmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeKiirooCmd:
				var msg KiirooCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeLinearCmd:
				var msg LinearCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeLog:
				var msg LogMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeOK:
				var msg OKMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypePing:
				var msg PingMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRequestDeviceList:
				var msg RequestDeviceListMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRequestLog:
				var msg RequestLogMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRequestServerInfo:
				var msg RequestServerInfoMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeRotateCmd:
				var msg RotateCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeServerInfo:
				var msg ServerInfoMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStartScanning:
				var msg StartScanningMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStopAllDevices:
				var msg StopAllDevicesMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStopDeviceCmd:
				var msg StopDeviceCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeStopScanning:
				var msg StopScanningMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeTest:
				var msg TestMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeVibrateCmd:
				var msg VibrateCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			case MessageTypeVorzeA10CycloneCmd:
				var msg VorzeA10CycloneCmdMessage
				if err := json.UnmarshalDecode(decoder, &msg); err != nil {
					return fmt.Errorf("failed to unmarshal message of type %q: %w", key, err)
				}
				*p = append(*p, &msg)

			default:
				v, err := decoder.ReadValue()
				if err != nil {
					return fmt.Errorf("failed to read unknown buttplug.io message type %q: %w", key, err)
				}
				slog.Warn(
					"received unknown buttplug.io message type, ignoring",
					slog.String("msg.type", key),
					slog.Any("msg.body", v))
			}

			// Advance reader out of the object body.
			if err = readTokenKind(jsontext.Kind('}')); err != nil {
				return fmt.Errorf("failed to read end of object token: %w", err)
			}
		}
	}
}

// MarshalJSONTo writes the payload as the JSON websocket wire protocol.
func (p Payload) MarshalJSONTo(encoder *jsontext.Encoder) error {
	if err := encoder.WriteToken(jsontext.BeginArray); err != nil {
		return fmt.Errorf("failed to write start of payload array token: %w", err)
	}

	for i, msg := range p {
		if err := encoder.WriteToken(jsontext.BeginObject); err != nil {
			return fmt.Errorf("failed to write start of message object token: %w", err)
		}

		if err := encoder.WriteToken(jsontext.String(string(msg.Type()))); err != nil {
			return fmt.Errorf("failed to write message type key token: %w", err)
		}

		if err := json.MarshalEncode(encoder, msg); err != nil {
			return fmt.Errorf("failed to marshal message[%d] (type %T): %w", i, msg, err)
		}

		if err := encoder.WriteToken(jsontext.EndObject); err != nil {
			return fmt.Errorf("failed to write end of message object token: %w", err)
		}
	}

	if err := encoder.WriteToken(jsontext.EndArray); err != nil {
		return fmt.Errorf("failed to write end of array token: %w", err)
	}

	return nil
}

// LogValue implements [slog.LogValuer].
func (p Payload) LogValue() slog.Value {
	attrs := make([]slog.Attr, len(p))
	for i, msg := range p {
		attrs[i] = slog.Any(fmt.Sprintf("payload[%d]", i), msg)
	}
	return slog.GroupValue(attrs...)
}

// Message represents a single message in the buttplug.io protocol.
//
// The following messages are defined:
//   - [DeviceAddedMessage]
//   - [DeviceListMessage]
//   - [DeviceRemovedMessage]
//   - [ErrorMessage]
//   - [FleshlightLaunchFW12CmdMessage]
//   - [KiirooCmdMessage]
//   - [LinearCmdMessage]
//   - [LogMessage]
//   - [OKMessage]
//   - [PingMessage]
//   - [RequestDeviceListMessage]
//   - [RequestLogMessage]
//   - [RequestServerInfoMessage]
//   - [RotateCmdMessage]
//   - [ServerInfoMessage]
//   - [StartScanningMessage]
//   - [StopAllDevicesMessage]
//   - [StopDeviceCmdMessage]
//   - [StopScanningMessage]
//   - [TestMessage]
//   - [VibrateCmdMessage]
//   - [VorzeA10CycloneCmdMessage]
type Message interface {
	// Type returns the message type of the message.
	Type() MessageType

	isMessage()
}

// ClientMessage represents a message that can be sent from the client to the server.
// It extends [Message] with a way to set the client ID to be used when sending the message.
//
// The following messages are defined:
//   - [DeviceListMessage]
//   - [FleshlightLaunchFW12CmdMessage]
//   - [KiirooCmdMessage]
//   - [LinearCmdMessage]
//   - [OKMessage]
//   - [PingMessage]
//   - [RequestDeviceListMessage]
//   - [RequestLogMessage]
//   - [RequestServerInfoMessage]
//   - [RotateCmdMessage]
//   - [ServerInfoMessage]
//   - [StartScanningMessage]
//   - [StopAllDevicesMessage]
//   - [StopDeviceCmdMessage]
//   - [StopScanningMessage]
//   - [TestMessage]
//   - [VibrateCmdMessage]
//   - [VorzeA10CycloneCmdMessage]
type ClientMessage interface {
	Message
	// ClientID returns the ID field of the message.
	ClientID() ClientID
	// WithID sets the ID field of the shallow-copied message and returns the modified message.
	WithID(id ClientID) ClientMessage

	isClientMessage()
}

// ServerMessage represents a message that can be sent from the server to the client.
// It extends [Message].
//
// The following messages are defined:
//   - [ErrorMessage]
type ServerMessage interface {
	Message
	// ServerID returns the ID field of the message.
	ServerID() ServerID

	isServerMessage()
}

// InternalMessage is a special type that the library uses for internal-only messages.
// Messages of this type were never emitted from the server.
type InternalMessage struct{}

func (i *InternalMessage) isMessage()         {}
func (i *InternalMessage) isInternalMessage() {}

// Type returns an empty string for internal messages.
func (m InternalMessage) Type() MessageType {
	return ""
}

// IsInternalMessage returns whether the message is an internal-only message.
func IsInternalMessage(m Message) bool {
	_, ok := m.(interface {
		isInternalMessage()
	})
	return ok
}

// MarshalJSON returns an error because internal messages cannot be marshaled.
func (m InternalMessage) MarshalJSON() ([]byte, error) {
	return nil, errors.New("internal messages cannot be marshaled")
}

// Type returns [MessageTypeDeviceAdded].
func (d *DeviceAddedMessage) Type() MessageType {
	return MessageTypeDeviceAdded
}

func (d *DeviceAddedMessage) isMessage() {}

// LogValue implements [slog.LogValuer].
func (d *DeviceAddedMessage) LogValue() slog.Value {
	type raw DeviceAddedMessage
	return slog.GroupValue(
		slog.String("type", "DeviceAdded"),
		slog.Any("data", (*raw)(d)))
}

// Type returns [MessageTypeDeviceList].
func (d *DeviceListMessage) Type() MessageType {
	return MessageTypeDeviceList
}

func (d *DeviceListMessage) isMessage()       {}
func (d *DeviceListMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (d *DeviceListMessage) ClientID() ClientID {
	return d.ID
}

// WithID implements [ClientMessage].
func (d *DeviceListMessage) WithID(id ClientID) ClientMessage {
	d.ID = id
	return d
}

// LogValue implements [slog.LogValuer].
func (d *DeviceListMessage) LogValue() slog.Value {
	type raw DeviceListMessage
	return slog.GroupValue(
		slog.String("type", "DeviceList"),
		slog.Any("data", (*raw)(d)))
}

// Type returns [MessageTypeDeviceRemoved].
func (d *DeviceRemovedMessage) Type() MessageType {
	return MessageTypeDeviceRemoved
}

func (d *DeviceRemovedMessage) isMessage() {}

// LogValue implements [slog.LogValuer].
func (d *DeviceRemovedMessage) LogValue() slog.Value {
	type raw DeviceRemovedMessage
	return slog.GroupValue(
		slog.String("type", "DeviceRemoved"),
		slog.Any("data", (*raw)(d)))
}

// Type returns [MessageTypeError].
func (e *ErrorMessage) Type() MessageType {
	return MessageTypeError
}

func (e *ErrorMessage) isMessage()       {}
func (e *ErrorMessage) isServerMessage() {}

// ServerID implements [ServerMessage]
func (e *ErrorMessage) ServerID() ServerID {
	return e.ID
}

// LogValue implements [slog.LogValuer].
func (e *ErrorMessage) LogValue() slog.Value {
	type raw ErrorMessage
	return slog.GroupValue(
		slog.String("type", "Error"),
		slog.Any("data", (*raw)(e)))
}

// Type returns [MessageTypeFleshlightLaunchFW12Cmd].
func (f *FleshlightLaunchFW12CmdMessage) Type() MessageType {
	return MessageTypeFleshlightLaunchFW12Cmd
}

func (f *FleshlightLaunchFW12CmdMessage) isMessage()       {}
func (f *FleshlightLaunchFW12CmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (f *FleshlightLaunchFW12CmdMessage) ClientID() ClientID {
	return f.ID
}

// WithID implements [ClientMessage].
func (f *FleshlightLaunchFW12CmdMessage) WithID(id ClientID) ClientMessage {
	f.ID = id
	return f
}

// LogValue implements [slog.LogValuer].
func (f *FleshlightLaunchFW12CmdMessage) LogValue() slog.Value {
	type raw FleshlightLaunchFW12CmdMessage
	return slog.GroupValue(
		slog.String("type", "FleshlightLaunchFW12Cmd"),
		slog.Any("data", (*raw)(f)))
}

// Type returns [MessageTypeKiirooCmd].
func (k *KiirooCmdMessage) Type() MessageType {
	return MessageTypeKiirooCmd
}

func (k *KiirooCmdMessage) isMessage()       {}
func (k *KiirooCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (k *KiirooCmdMessage) ClientID() ClientID {
	return k.ID
}

// WithID implements [ClientMessage].
func (k *KiirooCmdMessage) WithID(id ClientID) ClientMessage {
	k.ID = id
	return k
}

// LogValue implements [slog.LogValuer].
func (k *KiirooCmdMessage) LogValue() slog.Value {
	type raw KiirooCmdMessage
	return slog.GroupValue(
		slog.String("type", "KiirooCmd"),
		slog.Any("data", (*raw)(k)))
}

// Type returns [MessageTypeLinearCmd].
func (l *LinearCmdMessage) Type() MessageType {
	return MessageTypeLinearCmd
}

func (l *LinearCmdMessage) isMessage()       {}
func (l *LinearCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (l *LinearCmdMessage) ClientID() ClientID {
	return l.ID
}

// WithID implements [ClientMessage].
func (l *LinearCmdMessage) WithID(id ClientID) ClientMessage {
	l.ID = id
	return l
}

// LogValue implements [slog.LogValuer].
func (l *LinearCmdMessage) LogValue() slog.Value {
	type raw LinearCmdMessage
	return slog.GroupValue(
		slog.String("type", "LinearCmd"),
		slog.Any("data", (*raw)(l)))
}

// Type returns [MessageTypeLog].
func (l *LogMessage) Type() MessageType {
	return MessageTypeLog
}

func (l *LogMessage) isMessage() {}

// LogValue implements [slog.LogValuer].
func (l *LogMessage) LogValue() slog.Value {
	type raw LogMessage
	return slog.GroupValue(
		slog.String("type", "Log"),
		slog.Any("data", (*raw)(l)))
}

// Type returns [MessageTypeOK].
func (o *OKMessage) Type() MessageType {
	return MessageTypeOK
}

func (o *OKMessage) isMessage()       {}
func (o *OKMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (o *OKMessage) ClientID() ClientID {
	return o.ID
}

// WithID implements [ClientMessage].
func (o *OKMessage) WithID(id ClientID) ClientMessage {
	o.ID = id
	return o
}

// LogValue implements [slog.LogValuer].
func (o *OKMessage) LogValue() slog.Value {
	type raw OKMessage
	return slog.GroupValue(
		slog.String("type", "Ok"),
		slog.Any("data", (*raw)(o)))
}

// Type returns [MessageTypePing].
func (p *PingMessage) Type() MessageType {
	return MessageTypePing
}

func (p *PingMessage) isMessage()       {}
func (p *PingMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (p *PingMessage) ClientID() ClientID {
	return p.ID
}

// WithID implements [ClientMessage].
func (p *PingMessage) WithID(id ClientID) ClientMessage {
	p.ID = id
	return p
}

// LogValue implements [slog.LogValuer].
func (p *PingMessage) LogValue() slog.Value {
	type raw PingMessage
	return slog.GroupValue(
		slog.String("type", "Ping"),
		slog.Any("data", (*raw)(p)))
}

// Type returns [MessageTypeRequestDeviceList].
func (r *RequestDeviceListMessage) Type() MessageType {
	return MessageTypeRequestDeviceList
}

func (r *RequestDeviceListMessage) isMessage()       {}
func (r *RequestDeviceListMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RequestDeviceListMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RequestDeviceListMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RequestDeviceListMessage) LogValue() slog.Value {
	type raw RequestDeviceListMessage
	return slog.GroupValue(
		slog.String("type", "RequestDeviceList"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRequestLog].
func (r *RequestLogMessage) Type() MessageType {
	return MessageTypeRequestLog
}

func (r *RequestLogMessage) isMessage()       {}
func (r *RequestLogMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RequestLogMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RequestLogMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RequestLogMessage) LogValue() slog.Value {
	type raw RequestLogMessage
	return slog.GroupValue(
		slog.String("type", "RequestLog"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRequestServerInfo].
func (r *RequestServerInfoMessage) Type() MessageType {
	return MessageTypeRequestServerInfo
}

func (r *RequestServerInfoMessage) isMessage()       {}
func (r *RequestServerInfoMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RequestServerInfoMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RequestServerInfoMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RequestServerInfoMessage) LogValue() slog.Value {
	type raw RequestServerInfoMessage
	return slog.GroupValue(
		slog.String("type", "RequestServerInfo"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeRotateCmd].
func (r *RotateCmdMessage) Type() MessageType {
	return MessageTypeRotateCmd
}

func (r *RotateCmdMessage) isMessage()       {}
func (r *RotateCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (r *RotateCmdMessage) ClientID() ClientID {
	return r.ID
}

// WithID implements [ClientMessage].
func (r *RotateCmdMessage) WithID(id ClientID) ClientMessage {
	r.ID = id
	return r
}

// LogValue implements [slog.LogValuer].
func (r *RotateCmdMessage) LogValue() slog.Value {
	type raw RotateCmdMessage
	return slog.GroupValue(
		slog.String("type", "RotateCmd"),
		slog.Any("data", (*raw)(r)))
}

// Type returns [MessageTypeServerInfo].
func (s *ServerInfoMessage) Type() MessageType {
	return MessageTypeServerInfo
}

func (s *ServerInfoMessage) isMessage()       {}
func (s *ServerInfoMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *ServerInfoMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *ServerInfoMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *ServerInfoMessage) LogValue() slog.Value {
	type raw ServerInfoMessage
	return slog.GroupValue(
		slog.String("type", "ServerInfo"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStartScanning].
func (s *StartScanningMessage) Type() MessageType {
	return MessageTypeStartScanning
}

func (s *StartScanningMessage) isMessage()       {}
func (s *StartScanningMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StartScanningMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StartScanningMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StartScanningMessage) LogValue() slog.Value {
	type raw StartScanningMessage
	return slog.GroupValue(
		slog.String("type", "StartScanning"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStopAllDevices].
func (s *StopAllDevicesMessage) Type() MessageType {
	return MessageTypeStopAllDevices
}

func (s *StopAllDevicesMessage) isMessage()       {}
func (s *StopAllDevicesMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StopAllDevicesMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StopAllDevicesMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StopAllDevicesMessage) LogValue() slog.Value {
	type raw StopAllDevicesMessage
	return slog.GroupValue(
		slog.String("type", "StopAllDevices"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStopDeviceCmd].
func (s *StopDeviceCmdMessage) Type() MessageType {
	return MessageTypeStopDeviceCmd
}

func (s *StopDeviceCmdMessage) isMessage()       {}
func (s *StopDeviceCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StopDeviceCmdMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StopDeviceCmdMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StopDeviceCmdMessage) LogValue() slog.Value {
	type raw StopDeviceCmdMessage
	return slog.GroupValue(
		slog.String("type", "StopDeviceCmd"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeStopScanning].
func (s *StopScanningMessage) Type() MessageType {
	return MessageTypeStopScanning
}

func (s *StopScanningMessage) isMessage()       {}
func (s *StopScanningMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (s *StopScanningMessage) ClientID() ClientID {
	return s.ID
}

// WithID implements [ClientMessage].
func (s *StopScanningMessage) WithID(id ClientID) ClientMessage {
	s.ID = id
	return s
}

// LogValue implements [slog.LogValuer].
func (s *StopScanningMessage) LogValue() slog.Value {
	type raw StopScanningMessage
	return slog.GroupValue(
		slog.String("type", "StopScanning"),
		slog.Any("data", (*raw)(s)))
}

// Type returns [MessageTypeTest].
func (t *TestMessage) Type() MessageType {
	return MessageTypeTest
}

func (t *TestMessage) isMessage()       {}
func (t *TestMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (t *TestMessage) ClientID() ClientID {
	return t.ID
}

// WithID implements [ClientMessage].
func (t *TestMessage) WithID(id ClientID) ClientMessage {
	t.ID = id
	return t
}

// LogValue implements [slog.LogValuer].
func (t *TestMessage) LogValue() slog.Value {
	type raw TestMessage
	return slog.GroupValue(
		slog.String("type", "Test"),
		slog.Any("data", (*raw)(t)))
}

// Type returns [MessageTypeVibrateCmd].
func (v *VibrateCmdMessage) Type() MessageType {
	return MessageTypeVibrateCmd
}

func (v *VibrateCmdMessage) isMessage()       {}
func (v *VibrateCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (v *VibrateCmdMessage) ClientID() ClientID {
	return v.ID
}

// WithID implements [ClientMessage].
func (v *VibrateCmdMessage) WithID(id ClientID) ClientMessage {
	v.ID = id
	return v
}

// LogValue implements [slog.LogValuer].
func (v *VibrateCmdMessage) LogValue() slog.Value {
	type raw VibrateCmdMessage
	return slog.GroupValue(
		slog.String("type", "VibrateCmd"),
		slog.Any("data", (*raw)(v)))
}

// Type returns [MessageTypeVorzeA10CycloneCmd].
func (v *VorzeA10CycloneCmdMessage) Type() MessageType {
	return MessageTypeVorzeA10CycloneCmd
}

func (v *VorzeA10CycloneCmdMessage) isMessage()       {}
func (v *VorzeA10CycloneCmdMessage) isClientMessage() {}

// ClientID implements [ClientMessage]
func (v *VorzeA10CycloneCmdMessage) ClientID() ClientID {
	return v.ID
}

// WithID implements [ClientMessage].
func (v *VorzeA10CycloneCmdMessage) WithID(id ClientID) ClientMessage {
	v.ID = id
	return v
}

// LogValue implements [slog.LogValuer].
func (v *VorzeA10CycloneCmdMessage) LogValue() slog.Value {
	type raw VorzeA10CycloneCmdMessage
	return slog.GroupValue(
		slog.String("type", "VorzeA10CycloneCmd"),
		slog.Any("data", (*raw)(v)))
}

// DeviceAddedMessage: notifies client that a device of a certain type has been
// added to the server.
type DeviceAddedMessage struct {
	// ID: used for non-direct-reply messages that can only be sent from server
	// to client, using the reserved system message Id of 0.
	ID SystemID `json:"Id"`
	// DeviceName: name of the device.
	DeviceName DeviceName `json:"DeviceName"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// DeviceMessages: a list of the messages a device will accept on this
	// server implementation.
	DeviceMessages DeviceMessages `json:"DeviceMessages"`
}

// DeviceListMessage: list of all available devices known to the system.
type DeviceListMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// Devices: array of device ids and names.
	Devices []Device `json:"Devices"`
}

// DeviceRemovedMessage: notifies client that a device of a certain type has
// been removed from the server.
type DeviceRemovedMessage struct {
	// ID: used for non-direct-reply messages that can only be sent from server
	// to client, using the reserved system message Id of 0.
	ID SystemID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
}

// ErrorMessage: signifies the server encountered an error while processing the
// message indicated by the id.
type ErrorMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID           ServerID `json:"Id"`
	ErrorMessage string   `json:"ErrorMessage"`
	ErrorCode    float64  `json:"ErrorCode"`
}

// FleshlightLaunchFW12CmdMessage: sends speed and position command to the
// Fleshlight Launch Device denoted by the device index.
type FleshlightLaunchFW12CmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Speed at which to move to designated position.
	Speed int `json:"Speed"`
	// Position to which to move Fleshlight.
	Position int `json:"Position"`
}

// KiirooCmdMessage: sends a raw byte string to a Kiiroo Onyx/Pearl device.
type KiirooCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Command to send to Kiiroo device.
	Command string `json:"Command"`
}

// LinearCmdMessage: sends a linear movement command to a device that supports
// linear movements.
type LinearCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Vectors: device linear movement times (milliseconds) and positions
	// (floating point, 0 < x < 1) keyed on linear actuator number, stepping
	// will be device specific.
	Vectors []Vector `json:"Vectors"`
}

// LogMessage: log message from the server.
type LogMessage struct {
	// ID: used for non-direct-reply messages that can only be sent from server
	// to client, using the reserved system message Id of 0.
	ID SystemID `json:"Id"`
	// LogLevel: log level of message.
	LogLevel LogLevel `json:"LogLevel"`
	// LogMessage: log message from server.
	LogMessage string `json:"LogMessage"`
}

// OKMessage: signifies successful processing of the message indicated by the
// id.
type OKMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// PingMessage: connection keep-alive message.
type PingMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// RequestDeviceListMessage: request for the server to send a list of devices to
// the client.
type RequestDeviceListMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// RequestLogMessage: request for server to stream log messages of a certain
// level to client.
type RequestLogMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// LogLevel: maximum level of log message to receive.
	LogLevel RequestLogLevel `json:"LogLevel"`
}

// RequestServerInfoMessage: request server version, and relay client name.
type RequestServerInfoMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// ClientName: name of the client software.
	ClientName string `json:"ClientName"`
	// MessageVersion: message template version of the client software.
	MessageVersion int `json:"MessageVersion"`
}

// RotateCmdMessage: sends a rotate command to a device that supports rotation.
type RotateCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Rotations: device rotation speeds (floating point, 0 < x < 1) keyed on
	// rotator number, stepping will be device specific.
	Rotations []Rotation `json:"Rotations"`
}

// ServerInfoMessage: server version information, in Major.Minor.Build format.
type ServerInfoMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// MessageVersion: message template version of the server software.
	MessageVersion int `json:"MessageVersion"`
	// MaxPingTime: maximum time (in milliseconds) the server will wait between
	// ping messages from client before shutting down.
	MaxPingTime int `json:"MaxPingTime"`
	// MajorVersion: major version of server.
	MajorVersion int `json:"MajorVersion"`
	// MinorVersion: minor version of server.
	MinorVersion int `json:"MinorVersion"`
	// BuildVersion: build version of server.
	BuildVersion int `json:"BuildVersion"`
	// ServerName: name of the server. Can be 0-length.
	ServerName string `json:"ServerName"`
}

// StartScanningMessage: request for the server to start scanning for new
// devices.
type StartScanningMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// StopAllDevicesMessage: stops all actions currently being taken by all
// connected devices.
type StopAllDevicesMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// StopDeviceCmdMessage: stops the all actions currently being taken by a
// device.
type StopDeviceCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
}

// StopScanningMessage: request for the server to stop scanning for new devices.
type StopScanningMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
}

// TestMessage: used for connection/application testing. Causes server to echo
// back the string sent. Sending string of 'Error' will result in a server
// error. .
type TestMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// TestString: string to be echo'd back from server. Setting this to 'Error'
	// will cause an error to be thrown.
	TestString string `json:"TestString"`
}

// VibrateCmdMessage: sends a vibrate command to a device that supports
// vibration.
type VibrateCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Speeds: device vibration speeds (floating point, 0 < x < 1) keyed on
	// vibrator number, stepping will be device specific.
	Speeds []SpeedsItem `json:"Speeds"`
}

// VorzeA10CycloneCmdMessage: sends a raw byte string to a Kiiroo Onyx/Pearl
// device.
type VorzeA10CycloneCmdMessage struct {
	// ID: user-set id for the message. 0 denotes system message and is
	// reserved.
	ID ClientID `json:"Id"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// Speed: rotation speed command for the Cyclone.
	Speed int `json:"Speed"`
	// Clockwise: true for clockwise rotation (in relation to device facing
	// user), false for Counter-clockwise.
	Clockwise bool `json:"Clockwise"`
}

// SystemID: used for non-direct-reply messages that can only be sent from
// server to client, using the reserved system message Id of 0.
type SystemID int

// DeviceName: name of the device.
type DeviceName string

// DeviceIndex: index used for referencing the device in device messages.
type DeviceIndex int

// DeviceMessages: a list of the messages a device will accept on this server
// implementation.
type DeviceMessages struct {
	// FleshlightLaunchFW12Cmd: attributes for device message that have no
	// attributes.
	FleshlightLaunchFW12Cmd ptr.Optional[NullMessageAttributes] `json:"FleshlightLaunchFW12Cmd,omitzero"`
	// KiirooCmd: attributes for device message that have no attributes.
	KiirooCmd ptr.Optional[NullMessageAttributes] `json:"KiirooCmd,omitzero"`
	// LinearCmd: attributes for device messages.
	LinearCmd ptr.Optional[GenericMessageAttributes] `json:"LinearCmd,omitzero"`
	// LovenseCmd: attributes for device message that have no attributes.
	LovenseCmd ptr.Optional[NullMessageAttributes] `json:"LovenseCmd,omitzero"`
	// RotateCmd: attributes for device messages.
	RotateCmd ptr.Optional[GenericMessageAttributes] `json:"RotateCmd,omitzero"`
	// SingleMotorVibrateCmd: attributes for device message that have no
	// attributes.
	SingleMotorVibrateCmd ptr.Optional[NullMessageAttributes] `json:"SingleMotorVibrateCmd,omitzero"`
	// StopDeviceCmd: attributes for device message that have no attributes.
	StopDeviceCmd ptr.Optional[NullMessageAttributes] `json:"StopDeviceCmd,omitzero"`
	// VibrateCmd: attributes for device messages.
	VibrateCmd ptr.Optional[GenericMessageAttributes] `json:"VibrateCmd,omitzero"`
	// VorzeA10CycloneCmd: attributes for device message that have no
	// attributes.
	VorzeA10CycloneCmd ptr.Optional[NullMessageAttributes] `json:"VorzeA10CycloneCmd,omitzero"`
}

// ClientID: user-set id for the message. 0 denotes system message and is
// reserved.
type ClientID int

type Device struct {
	// DeviceName: name of the device.
	DeviceName DeviceName `json:"DeviceName"`
	// DeviceIndex: index used for referencing the device in device messages.
	DeviceIndex DeviceIndex `json:"DeviceIndex"`
	// DeviceMessages: a list of the messages a device will accept on this
	// server implementation.
	DeviceMessages DeviceMessages `json:"DeviceMessages"`
}

// ServerID: user-set id for the message. 0 denotes system message and is
// reserved.
type ServerID int

type Vector struct {
	// Index: linear actuator number.
	Index int `json:"Index"`
	// Duration: linear movement time in milliseconds.
	Duration float64 `json:"Duration"`
	// Position: linear movement position (floating point, 0 < x < 1), stepping
	// will be device specific.
	Position float64 `json:"Position"`
}

// LogLevel: log level of message.
type LogLevel string

// Enumeration values for [LogLevel] of [Log].
const (
	LogLevelOff   LogLevel = "Off"
	LogLevelFatal LogLevel = "Fatal"
	LogLevelError LogLevel = "Error"
	LogLevelWarn  LogLevel = "Warn"
	LogLevelInfo  LogLevel = "Info"
	LogLevelDebug LogLevel = "Debug"
	LogLevelTrace LogLevel = "Trace"
)

// LogLevel: maximum level of log message to receive.
type RequestLogLevel string

// Enumeration values for [RequestLogLevel] of [RequestLog].
const (
	RequestLogLevelOff   RequestLogLevel = "Off"
	RequestLogLevelFatal RequestLogLevel = "Fatal"
	RequestLogLevelError RequestLogLevel = "Error"
	RequestLogLevelWarn  RequestLogLevel = "Warn"
	RequestLogLevelInfo  RequestLogLevel = "Info"
	RequestLogLevelDebug RequestLogLevel = "Debug"
	RequestLogLevelTrace RequestLogLevel = "Trace"
)

type Rotation struct {
	// Index: rotator number.
	Index int `json:"Index"`
	// Speed: rotation speed (floating point, 0 < x < 1), stepping will be
	// device specific.
	Speed float64 `json:"Speed"`
	// Clockwise: rotation direction (boolean). Not all devices have a concept
	// of actual clockwise.
	Clockwise bool `json:"Clockwise"`
}

type SpeedsItem struct {
	// Index: vibrator number.
	Index int `json:"Index"`
	// Speed: vibration speed (floating point, 0 < x < 1), stepping will be
	// device specific.
	Speed float64 `json:"Speed"`
}

// NullMessageAttributes: attributes for device message that have no attributes.
type NullMessageAttributes struct{}

// GenericMessageAttributes: attributes for device messages.
type GenericMessageAttributes struct {
	// FeatureCount: number of features on device.
	FeatureCount ptr.Optional[FeatureCount] `json:"FeatureCount,omitzero"`
}

// FeatureCount: number of features on device.
type FeatureCount int
