package main

import (
	"flag"
	"fmt"
	"log"
	"log/slog"
	"os"
	"path"

	j "github.com/dave/jennifer/jen"
	"github.com/davecgh/go-spew/spew"
	"github.com/lmittmann/tint"
	"libdb.so/go-buttplug/cmd/buttplug-generate/jsonschema"
)

const (
	packageName   = "schema"
	headerComment = `// Code generated by buttplug-generate; DO NOT EDIT.`
)

var (
	schemaPath = "./buttplug-schema.json"
	outputDir  = "./"
	quiet      = false
)

func init() {
	flag.StringVar(&schemaPath, "schema", schemaPath, "Path to the Buttplug schema JSON file.")
	flag.StringVar(&outputDir, "outdir", outputDir, "Directory to output the generated code.")
	flag.BoolVar(&quiet, "quiet", quiet, "If set, suppress non-error log output.")
}

var (
	spew0 = &spew.ConfigState{Indent: "  ", DisableCapacities: true, DisablePointerAddresses: true, MaxDepth: 0}
	spew1 = &spew.ConfigState{Indent: "  ", DisableCapacities: true, DisablePointerAddresses: true, MaxDepth: 1}
	spew2 = &spew.ConfigState{Indent: "  ", DisableCapacities: true, DisablePointerAddresses: true, MaxDepth: 2}
)

func main() {
	log.SetFlags(0)
	flag.Parse()

	level := slog.LevelWarn
	if !quiet {
		level = slog.LevelDebug
	}

	tintHandler := tint.NewHandler(os.Stderr, &tint.Options{
		Level: level,
	})
	logger := slog.New(tintHandler)
	slog.SetDefault(logger)

	schema, err := jsonschema.ParseFile(schemaPath)
	if err != nil {
		slog.Error(
			"cannot compile jsonschema file",
			"file", schemaPath,
			"err", err)
		os.Exit(1)
	}

	// Import guard:
	_ = spew.Config

	for _, messageSchema := range schema.AnyOf() {
		messageSchema = messageSchema.Unref()

		messageVersion, err := parseMessageSpecVersion(messageSchema)
		if err != nil {
			slog.Error(
				"cannot parse message spec version; something changed! exiting",
				"location", messageSchema.Location,
				"err", err)
			os.Exit(1)
		}

		outPath := fmt.Sprintf("%s/v%d/%s.gen.go", outputDir, messageVersion, packageName)
		if err := os.MkdirAll(path.Dir(outPath), 0o755); err != nil {
			slog.Error(
				"cannot create output directory",
				"dir", path.Dir(outPath),
				"err", err)
			os.Exit(1)
		}

		slog := slog.With(
			"version", messageVersion)
		slog.Info(
			"generating message schema",
			"location", messageSchema.Location(),
			"version", messageVersion,
			"out", outPath)

		file := j.NewFile(packageName)
		file.HeaderComment(headerComment)
		file.PackageComment(fmt.Sprintf(
			"Package %s contains the Buttplug message schema for version %d.",
			packageName, messageVersion,
		))

		gen := newGenerator(file)
		gen.generate(messageSchema)

		if err := file.Save(outPath); err != nil {
			slog.Error(
				"file generated had errors, but proceeding to render anyway for debugging purposes")
			file.NoFormat = true
		}

		if err := file.Save(outPath); err != nil {
			slog.Error(
				"cannot save generated file",
				"file", outPath,
				"err", "<see below>")
			fmt.Fprint(os.Stderr, err)
			os.Exit(1)
		}
	}
}

func parseMessageSpecVersion(schema *jsonschema.Schema) (int, error) {
	base := schema.Location().BaseName()
	var version int
	if _, err := fmt.Sscanf(base, "MessageSpecV%d", &version); err != nil {
		return 0, fmt.Errorf("cannot extract version out of message name %q", base)
	}
	return version, nil
}
